In [2]:
import sys
import os
from pathlib import Path

notebook_dir = Path(os.getcwd())
project_root = notebook_dir.parent
src_dir      = project_root / "src"

if str(src_dir) not in sys.path:
    sys.path.insert(0, str(src_dir))

from config_loader import load_config
import triage_filter

cfg = load_config()

# Resolve triage path (new key — created by run_triage if absent)
triage_path = Path(cfg["paths"]["triage"])

print("Config loaded.")
print("  raw_images :", cfg["paths"]["raw_images"])
print("  triage     :", triage_path)

Config loaded.
  raw_images : /mnt/storage_11tb/Drive_files_to_syncronize/3 - Images DataSets & Labelling Outputs/1639_DS/raw
  triage     : /mnt/storage_11tb/Drive_files_to_syncronize/3 - Images DataSets & Labelling Outputs/1639_DS/triage

# Stage 00a.2 — SigLIP Triage Filter

**What this notebook does:**  
Scores every raw patent image with [SigLIP](https://huggingface.co/timm/ViT-SO400M-14-SigLIP-384) (a large vision-language model) to detect images that are **not technical drawings** — tables, text pages, data grids, title sheets — before those images enter the expensive labelling pipeline downstream.

It is **completely non-destructive**: nothing in `raw/` is touched. Outputs are JSON/CSV manifests only.

---

## Why this step exists

PatSeer downloads *everything* on the Drawings tab — which often includes:
- Cover pages / title sheets
- Tables of component labels
- Text-only description pages
- Flowcharts and block diagrams that look like drawings but aren't figure crops

Running `00b` (figure crop + label matching) on those wastes GPU time and pollutes the labelled dataset. This step flags them so Stage `00b` can skip them.

---

## How the scoring works

Each image is scored against two zero-shot text prompts using SigLIP:

| Prompt | Meaning |
|--------|---------|
| `"a technical patent line drawing of an aircraft or mechanical component"` | → `score_drawing` |
| `"a table, chart, text page, or data grid with no technical drawing"` | → `score_table` |

The two scores are softmax-normalised so they sum to 1.  
`keep = True` when `score_drawing ≥ threshold` (default **0.60**).  
`keep = False` = flagged as non-drawing → will be skipped by `00b`.

> **Threshold guide:**  
> `0.60` (default) — conservative, keeps borderline images, low false-positive rate  
> `0.65` — moderate filtering  
> `0.70` — aggressive, only keep high-confidence drawings

---

## Outputs

Both written under `cfg["paths"]["triage"]` = `1639_DS/triage/`:

| File | Content |
|------|---------|
| `<patent_id>.json` | Per-image scores for one patent: `file`, `pred`, `score_drawing`, `score_table`, `keep` |
| `triage_summary.csv` | One row per patent: `patent_id`, `total_images`, `flagged_count`, `flagged_ratio` |

Already-processed patents are **not re-scored** on repeat runs (JSON exists → skip).

---

## Where it fits in the pipeline

```
00a    (download from PatSeer)
 ↓
00a.1  (audit: which patents are missing / need re-download)
 ↓
00a.2  ← YOU ARE HERE  (score every image: drawing vs. non-drawing)
 ↓
00b    (figure crop + _F/_Fu label matching — uses triage to skip flagged images)
 ↓
02     (pad + resize to 518×518)
```

---

## Cell guide

| Cell | What it does |
|------|--------------|
| 1 | Load config — resolves `raw_images` and `triage` paths |
| 2 | Load SigLIP model (~3 GB weights, cached after first run, needs GPU) |
| 3 | Run triage — set `limit=10` to test on 10 patents first, `limit=None` for full dataset |
| 4 | Inspect results — flagged ratio summary + per-image table for worst patents |

---

## Before you run

- **GPU required** — SigLIP ViT-SO400M is large; CPU inference is very slow (~10 s/image).  
- **First run downloads ~3 GB** of weights into the HuggingFace cache (`~/.cache/huggingface/`).  
- Run Cell 3 with `limit=10` first to check the threshold is sensible for your data before processing all 1350 folders.  
- If scores cluster around 0.50–0.52 (as in the test output above), the prompts may need tuning for your specific patent images — see `src/triage_filter.py` → `_PROMPT_KEEP` / `_PROMPT_FLAG`.

In [2]:
# Loads SigLIP ViT-SO400M-14-SigLIP-384 via open_clip.
# Downloads ~3 GB of weights on first run (cached by HuggingFace Hub).
model, processor, device = triage_filter.load_siglip_model(cfg)
print(f"SigLIP ready on: {device}")

[SigLIP] Cache: /home/vasco/Vasco Workspace/Tese_Vasco_Lnx/Patent-Labelling-Tools/models/SigLIP
[SigLIP] Loaded fp16 on cuda:0  (6.8 GB VRAM remaining)
SigLIP ready on: cuda:0

In [ ]:
# ── Run options ──────────────────────────────────────────────────────────────
#
# This cell runs SigLIP scoring — slow, and only needed ONCE per patent (or
# when new patent folders are added). Already-triaged patents are skipped by
# default so locked review decisions are never touched.
#
# To just change the keep/discard threshold on already-scored images, do NOT
# run this cell — use Cell 3b below instead (rethreshold_existing / reset_threshold),
# which is instant and never re-runs the model.
#
TEST_MODE  = False   # True = only 10 patents (quick sanity check)
                    # False = full dataset (all ~1614 folders)
THRESHOLD  = 0.53   # kept for API compatibility; logic now uses pure argmax
                    # (discard only when model prefers the table/text prompt)
FORCE      = False  # True = re-score and OVERWRITE already-triaged patents,
                    # destroying any locked review decisions. Only use this
                    # intentionally (e.g. raw images changed).
# ─────────────────────────────────────────────────────────────────────────────

limit = 600 if TEST_MODE else None
print(f"Running triage: {'TEST MODE (10 patents)' if TEST_MODE else 'FULL DATASET'}, threshold={THRESHOLD}")
triage_filter.run_triage(cfg, threshold=THRESHOLD, limit=limit, force=FORCE)

Running triage: FULL DATASET, threshold=0.53
[SigLIP] Cache: /home/vasco/Vasco Workspace/Tese_Vasco_Lnx/Patent-Labelling-Tools/models/SigLIP
[SigLIP] Loaded fp16 on cuda:1  (6.4 GB VRAM remaining)
  ✓ AT503689A1_38777771  total=2  flagged=2
  ✓ AU2020100605A4_70776151  total=12  flagged=12
  ✓ AU2021232803A1_85775850  total=10  flagged=10
  ✓ AU2023270571A1_95939416  total=4  flagged=4
  ✓ BR112023017877B1_83067308  total=7  flagged=7
  ✓ CA2869734A1_49882410  total=10  flagged=9
  ✓ CA2874341A1_50068674  total=10  flagged=10
  ✓ CA2947683A1_62068329  total=5  flagged=5
  ✓ CA2958445A1_63166000  total=5  flagged=5
  ✓ CA2963502A1_63709012  total=2  flagged=2
  ✓ CA2967221A1_58707420  total=11  flagged=11
  ✓ CA2967228A1_58707421  total=11  flagged=11
  ✓ CA2967402A1_58709316  total=12  flagged=12
  ✓ CA3096221A1_81206876  total=41  flagged=40
  ✓ CN101885295A_43071443  total=12  flagged=11
  ✓ CN103786881A_50663046  total=12  flagged=12
  ✓ CN104229137A_52218225  total=9  flagged=9
  ✓ CN105730692A_56254804  total=5  flagged=5
  ✓ CN105799934A_56467513  total=9  flagged=9
  ✓ CN105836109A_56597035  total=4  flagged=4
  ✓ CN105836121A_56597616  total=5  flagged=5
  ✓ CN105923154A_56832133  total=2  flagged=2
  ✓ CN106005373A_57096574  total=12  flagged=12
  ✓ CN106005387A_57116011  total=6  flagged=6
  ✓ CN106043685A_57172473  total=3  flagged=3
  ✓ CN106143900A_57353415  total=3  flagged=3
  ✓ CN106218887A_57553770  total=3  flagged=3
  ✓ CN106314794A_57819675  total=7  flagged=7
  ✓ CN106494614A_58323847  total=7  flagged=7
  ✓ CN106585976A_58594339  total=7  flagged=7
  ✓ CN106628168A_58813122  total=6  flagged=6
  ✓ CN106828919A_59128637  total=3  flagged=3
  ✓ CN106828920A_59128516  total=5  flagged=5
  ✓ CN106864746A_59166843  total=3  flagged=3
  ✓ CN106882372A_59180265  total=5  flagged=5
  ✓ CN106882373A_59179679  total=7  flagged=7
  ✓ CN106927040A_59423690  total=3  flagged=3
  ✓ CN106938701A_59469510  total=3  flagged=3
  ✓ CN106965928A_59329348  total=3  flagged=3
  ✓ CN107010180A_59439863  total=3  flagged=3
  ✓ CN107499513A_60694792  total=8  flagged=8
  ✓ CN107521686A_60748639  total=12  flagged=12
  ✓ CN107856855A_61701792  total=3  flagged=3
  ✓ CN108163193A_62514191  total=10  flagged=10
  ✓ CN108382580A_63070285  total=3  flagged=3
  ✓ CN108394557A_63092231  total=3  flagged=3
  ✓ CN108408043A_63129567  total=6  flagged=6
  ✓ CN108502167A_63373209  total=10  flagged=10
  ✓ CN108657426A_63776108  total=2  flagged=2
  ✓ CN108674654A_63802184  total=7  flagged=5
  ✓ CN108688803A_63850917  total=9  flagged=7
  ✓ CN108706104A_63866485  total=3  flagged=3
  ✓ CN108750103A_64021047  total=7  flagged=7
  ✓ CN108791876A_64069836  total=7  flagged=6
  ✓ CN108928471A_64445223  total=4  flagged=4
  ✓ CN109080824A_64794656  total=5  flagged=5
  ✓ CN109159890A_64876160  total=5  flagged=5
  ✓ CN109250104A_65043046  total=5  flagged=5
  ✓ CN109263898A_65195149  total=5  flagged=5
  ✓ CN109263903A_65194081  total=3  flagged=3
  ✓ CN109263905A_65195087  total=4  flagged=4
  ✓ CN109263907A_65195107  total=5  flagged=5
  ✓ CN109263908A_65195091  total=5  flagged=5
  ✓ CN109263910A_65195111  total=3  flagged=3
  ✓ CN109263914A_65194224  total=3  flagged=3
  ✓ CN109263926A_65195026  total=3  flagged=3
  ✓ CN109263932A_65194174  total=3  flagged=3
  ✓ CN109263945A_65194575  total=5  flagged=5
  ✓ CN109263947A_65195536  total=4  flagged=3
  ✓ CN109263949A_65195581  total=3  flagged=3
  ✓ CN109263950A_65195607  total=5  flagged=5
  ✓ CN109263951A_65195620  total=5  flagged=5
  ✓ CN109263953A_65195611  total=6  flagged=6
  ✓ CN109263956A_65195617  total=4  flagged=3
  ✓ CN109263958A_65195597  total=6  flagged=6
  ✓ CN109263959A_65195626  total=7  flagged=7
  ✓ CN109263961A_65195213  total=4  flagged=4
  ✓ CN109263962A_65195623  total=5  flagged=5
  ✓ CN109263968A_65195038  total=4  flagged=4
  ✓ CN109263969A_65195023  total=2  flagged=2
  ✓ CN109263972A_65194142  total=6  flagged=6
  ✓ CN109263981A_65194117  total=4  flagged=4
  ✓ CN109606635A_66017023  total=6  flagged=6
  ✓ CN109649648A_66120126  total=7  flagged=7
  ✓ CN109649650A_66118263  total=5  flagged=5
  ✓ CN110040248A_67279985  total=6  flagged=6
  ✓ CN110155317A_67634276  total=3  flagged=3
  ✓ CN110282126A_68002328  total=6  flagged=6
  ✓ CN110450948A_68487714  total=5  flagged=5
  ✓ CN110450949A_68487715  total=2  flagged=2
  ✓ CN110588948A_68850154  total=5  flagged=5
  ✓ CN110626494A_68972200  total=4  flagged=4
  ✓ CN111056002A_70307649  total=6  flagged=6
  ✓ CN111137447A_70526232  total=10  flagged=10
  ✓ CN111137448A_70526233  total=12  flagged=12
  ✓ CN111137449A_70526239  total=12  flagged=12
  ✓ CN111137450A_70526335  total=12  flagged=12
  ✓ CN111137451A_70526365  total=10  flagged=10
  ✓ CN111137452A_70526339  total=10  flagged=10
  ✓ CN111232196A_70878987  total=5  flagged=5
  ✓ CN111301676A_69844594  total=12  flagged=9
  ✓ CN111532426A_71969677  total=7  flagged=7
  ✓ CN111619804A_72255834  total=7  flagged=7
  ✓ CN111731475A_72653549  total=7  flagged=7
  ✓ CN111731476A_72648791  total=9  flagged=9
  ✓ CN111762314A_72723670  total=9  flagged=9
  ✓ CN111846213A_72948100  total=10  flagged=10
  ✓ CN111874224A_73199342  total=4  flagged=4
  ✓ CN111874226A_73151682  total=11  flagged=11
  ✓ CN111891344A_73230637  total=10  flagged=10
  ✓ CN112061386A_73682875  total=7  flagged=7
  ✓ CN112124592A_73844585  total=8  flagged=8
  ✓ CN112141347A_73954358  total=5  flagged=5
  ✓ CN112478154A_74940243  total=6  flagged=6
  ✓ CN112623209A_75290300  total=8  flagged=8
  ✓ CN112896499A_76107874  total=3  flagged=0
  ✓ CN113022848A_76456796  total=9  flagged=9
  ✓ CN113086183A_76679366  total=4  flagged=4
  ✓ CN113086184A_76679591  total=7  flagged=7
  ✓ CN113247244A_77180817  total=4  flagged=4
  ✓ CN113306714A_77381678  total=12  flagged=12
  ✓ CN113335501A_77479862  total=12  flagged=12
  ✓ CN113443135A_74346821  total=7  flagged=7
  ✓ CN113460300A_77866599  total=11  flagged=11
  ✓ CN113525678A_78093370  total=5  flagged=5
  ✓ CN113716033A_78681585  total=12  flagged=12
  ✓ CN113799970A_78938278  total=9  flagged=9
  ✓ CN113844647A_78974750  total=7  flagged=7
  ✓ CN113844648A_78979179  total=12  flagged=2
  ✓ CN113998098A_79930776  total=4  flagged=4
  ✓ CN114056558A_80278975  total=7  flagged=7
  ✓ CN114180048A_80545243  total=5  flagged=5
  ✓ CN114248915A_80791501  total=3  flagged=3
  ✓ CN114394232A_81232753  total=7  flagged=7
  ✓ CN114435591A_81374329  total=11  flagged=11
  ✓ CN114449860A_81372043  total=10  flagged=10
  ✓ CN114620226A_81899069  total=11  flagged=11
  ✓ CN114684361A_82142492  total=4  flagged=4
  ✓ CN114735209A_82278637  total=5  flagged=5
  ✓ CN114802735A_82535421  total=10  flagged=10
  ✓ CN114802742A_82531591  total=7  flagged=7
  ✓ CN114954905A_82985117  total=12  flagged=12
  ✓ CN115092392A_83287530  total=7  flagged=7
  ✓ CN115180142A_83512925  total=12  flagged=12
  ✓ CN115258146A_83757607  total=11  flagged=8
  ✓ CN115285345A_83825460  total=9  flagged=6
  ✓ CN115303479A_83867082  total=11  flagged=11
  ✓ CN115447786A_84310486  total=9  flagged=9
  ✓ CN115583348A_84771519  total=12  flagged=12
  ✓ CN116215850A_86583598  total=3  flagged=3
  ✓ CN116280175A_86802222  total=2  flagged=2
  ✓ CN116280179A_86786318  total=12  flagged=12
  ✓ CN116374167A_86965726  total=7  flagged=7
  ✓ CN116443246A_87134591  total=9  flagged=9
  ✓ CN116513455A_87400372  total=6  flagged=6
  ✓ CN116692003A_87830214  total=10  flagged=10
  ✓ CN117048822A_88658269  total=9  flagged=3
  ✓ CN117184468A_89004092  total=12  flagged=12
  ✓ CN117341965A_89362694  total=11  flagged=11
  ✓ CN117360784A_89400152  total=12  flagged=12
  ✓ CN117465666A_89624985  total=9  flagged=9
  ✓ CN117465668A_89639513  total=7  flagged=7
  ✓ CN117566089A_89894246  total=10  flagged=10
  ✓ CN117682065A_90135464  total=3  flagged=3
  ✓ CN117799494A_90431947  total=4  flagged=4
  ✓ CN117842351A_90542130  total=10  flagged=10
  ✓ CN117985223A_90897714  total=11  flagged=9
  ✓ CN118025467A_90982835  total=6  flagged=6
  ✓ CN118083120A_91143746  total=11  flagged=11
  ✓ CN118124795A_91231148  total=9  flagged=9
  ✓ CN118323437A_91770425  total=8  flagged=8
  ✓ CN118343291A_91813832  total=12  flagged=10
  ✓ CN118439173A_92319228  total=6  flagged=6
  ✓ CN118457914A_92156665  total=10  flagged=10
  ✓ CN118494752A_92240808  total=12  flagged=12
  ✓ CN118618608A_92601088  total=12  flagged=12
  ✓ CN118701285A_92811088  total=7  flagged=7
  ✓ CN118723072A_92853893  total=5  flagged=5
  ✓ CN118723073A_92861725  total=8  flagged=8
  ✓ CN118770544A_92984157  total=4  flagged=1
  ✓ CN118770545A_92996907  total=8  flagged=3
  ✓ CN118811082A_93068608  total=3  flagged=3
  ✓ CN118877199A_93227783  total=5  flagged=5
  ✓ CN118992092A_93474531  total=3  flagged=3
  ✓ CN119018344A_93527803  total=7  flagged=7
  ✓ CN119099860A_93717638  total=12  flagged=12
  ✓ CN119190349A_94058635  total=10  flagged=10
  ✓ CN119190372A_94061817  total=12  flagged=12
  ✓ CN119190373A_94076509  total=12  flagged=12
  ✓ CN119218412A_94040782  total=12  flagged=12
  ✓ CN119218413A_94069178  total=12  flagged=12
  ✓ CN119218430A_94068930  total=12  flagged=12
  ✓ CN119218431A_94048691  total=12  flagged=12
  ✓ CN119218432A_93946987  total=12  flagged=12
  ✓ CN119218433A_94070641  total=12  flagged=12
  ✓ CN119231792A_93946991  total=12  flagged=12
  ✓ CN119231793A_94070640  total=12  flagged=12
  ✓ CN119231794A_93945313  total=12  flagged=12
  ✓ CN119239921A_94035552  total=12  flagged=12
  ✓ CN119239928A_94035694  total=9  flagged=6
  ✓ CN119239935A_94032581  total=11  flagged=11
  ✓ CN119239958A_94018389  total=12  flagged=12
  ✓ CN119262274A_94112956  total=12  flagged=12
  ✓ CN119262283A_94107470  total=6  flagged=6
  ✓ CN119262284A_94110123  total=8  flagged=8
  ✓ CN119460096A_94582017  total=6  flagged=6
  ✓ CN119460097A_94575479  total=5  flagged=5
  ✓ CN119489922A_94628350  total=5  flagged=5
  ✓ CN119568404A_94796479  total=7  flagged=7
  ✓ CN119611751A_94888679  total=4  flagged=4
  ✓ CN119611752A_94907377  total=7  flagged=3
  ✓ CN119872875A_95436262  total=12  flagged=12
  ✓ CN120024492A_95735420  total=11  flagged=11
  ✓ CN120033940A_95736108  total=9  flagged=9
  ✓ CN120096806A_95877323  total=5  flagged=5
  ✓ CN120096807A_95888217  total=5  flagged=5
  ✓ CN120135432A_95951004  total=5  flagged=5
  ✓ CN120171750A_96042187  total=8  flagged=8
  ✓ CN120191516A_96063272  total=12  flagged=12
  ✓ CN120229361A_96157381  total=8  flagged=8
  ✓ CN120270494A_96243410  total=7  flagged=5
  ✓ CN120270503A_96245444  total=12  flagged=12
  ✓ CN120288238A_96267548  total=12  flagged=12
  ✓ CN120397241A_96504638  total=9  flagged=8
  ✓ CN120397245A_96510287  total=11  flagged=11
  ✓ CN120423050A_96563021  total=3  flagged=3
  ✓ CN120482345A_96675626  total=12  flagged=12
  ✓ CN120503960A_96714318  total=5  flagged=5
  ✓ CN120517586A_96742899  total=12  flagged=12
  ✓ CN120697951A_97109777  total=9  flagged=9
  ✓ CN120716940A_97161145  total=12  flagged=12
  ✓ CN120735960A_97182431  total=12  flagged=12
  ✓ CN120735961A_97198381  total=9  flagged=9
  ✓ CN120793159A_97308918  total=6  flagged=6
  ✓ CN120817242A_97375279  total=8  flagged=8
  ✓ CN120828942A_97399306  total=9  flagged=9
  ✓ CN120863861A_97470266  total=6  flagged=6
  ✓ CN120863865A_97459321  total=10  flagged=8
  ✓ CN120863869A_97470200  total=6  flagged=6
  ✓ CN120887008A_97503485  total=7  flagged=7
  ✓ CN120922344A_97594394  total=12  flagged=12
  ✓ CN120922349A_97583461  total=8  flagged=8
  ✓ CN121158211A_98041733  total=8  flagged=8
  ✓ CN121224978A_98148467  total=6  flagged=6
  ✓ CN121376154A_98460140  total=12  flagged=12
  ✓ CN121448607A_98587661  total=8  flagged=5
  ✓ CN121530138A_98711939  total=11  flagged=11
  ✓ CN121650868A_98986873  total=9  flagged=9
  ✓ CN121671872A_99028991  total=12  flagged=12
  ✓ CN121822815A_99339917  total=7  flagged=7
  ✓ CN121871769A_99419901  total=12  flagged=12
  ✓ CN202728574U_47654301  total=7  flagged=7
  ✓ CN206511122U_59867587  total=5  flagged=5
  ✓ CN218288104U_84809563  total=12  flagged=6
  ✓ CZ2023513A3_96171384  total=11  flagged=11
  ✓ DE102007055313A1_40576821  total=11  flagged=10
  ✓ DE102008044812A1_40530774  total=1  flagged=1
  ✓ DE102012020498A1_50436711  total=6  flagged=6
  ✓ DE102013001852A1_51163257  total=2  flagged=2
  ✓ DE102015000703A1_56293457  total=4  flagged=4
  ✓ DE102015017425B3_85284263  total=12  flagged=12
  ✓ DE102015105976A1_57043797  total=4  flagged=4
  ✓ DE102016001771A1_57630429  total=7  flagged=7
  ✓ DE102016011273A1_61301942  total=3  flagged=3
  ✓ DE102016015461A1_59010570  total=4  flagged=4
  ✓ DE102017122359A1_63914990  total=5  flagged=4
  ✓ DE102017123536A1_65817278  total=3  flagged=3
  ✓ DE102018100230A1_66995223  total=5  flagged=5
  ✓ DE102018113265A1_68576139  total=6  flagged=4
  ✓ DE102018116149A1_68943504  total=2  flagged=2
  ✓ DE102018116150A1_68943533  total=2  flagged=2
  ✓ DE102018116151A1_68943534  total=2  flagged=2
  ✓ DE102018116153A1_68943509  total=5  flagged=5
  ✓ DE102018116154A1_68943485  total=3  flagged=3
  ✓ DE102018116155A1_68943481  total=3  flagged=3
  ✓ DE102018116157A1_68943517  total=2  flagged=2
  ✓ DE102018116158A1_68943520  total=2  flagged=2
  ✓ DE102018116160A1_68943540  total=2  flagged=2
  ✓ DE102018116161A1_68943523  total=3  flagged=3
  ✓ DE102018116165A1_68943541  total=2  flagged=2
  ✓ DE102018116166A1_68943542  total=3  flagged=3
  ✓ DE102018116170A1_68943547  total=2  flagged=2
  ✓ DE102018116172A1_68943552  total=2  flagged=2
  ✓ DE102018123470A1_69725547  total=6  flagged=6
  ✓ DE102018130822A1_70681344  total=2  flagged=2
  ✓ DE102019001240A1_71843474  total=4  flagged=4
  ✓ DE102019001834A1_72240932  total=11  flagged=11
  ✓ DE102019004808A1_74092519  total=3  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ DE102019006484B3_71615573  total=12  flagged=12
  ✓ DE102019007020A1_75156016  total=12  flagged=12
  ✓ DE102019009187A1_73747659  total=1  flagged=1
  ✓ DE102019101358A1_71402602  total=1  flagged=1
  ✓ DE102019101359A1_71403069  total=4  flagged=4
  ✓ DE102019101362A1_71402646  total=3  flagged=3
  ✓ DE102019102189A1_67224462  total=5  flagged=4
  ✓ DE102019118023B3_71402838  total=5  flagged=5
  ✓ DE102019118024A1_74092679  total=2  flagged=2
  ✓ DE102019121788A1_74239987  total=2  flagged=2
  ✓ DE102020007834A1_81847393  total=8  flagged=8
  ✓ DE102020007836A1_81847214  total=8  flagged=8
  ✓ DE102020107437A1_77552521  total=3  flagged=3
  ✓ DE102020113488A1_78408629  total=12  flagged=12
  ✓ DE102020118674A1_79020761  total=3  flagged=3
  ✓ DE102020118677A1_79020751  total=2  flagged=2
  ✓ DE102020202612A1_73790105  total=4  flagged=4
  ✓ DE102021113538A1_81851524  total=3  flagged=3
  ✓ DE102023108565B3_89508163  total=6  flagged=6
  ✓ DE102023122141A1_94391001  total=2  flagged=2
  ✓ DE102023122145A1_94391062  total=3  flagged=3
  ✓ DE102023122146A1_94391408  total=4  flagged=4
  ✓ DE102023129326A1_95342019  total=3  flagged=3
  ✓ DE102023130037B3_91852679  total=2  flagged=2
  ✓ DE102023133781B3_94170746  total=3  flagged=3
  ✓ DE102023135708A1_93650362  total=7  flagged=4
  ✓ DE102024102439A1_96347327  total=3  flagged=3
  ✓ DE102024102441A1_96347471  total=3  flagged=3
  ✓ DE102024103065B3_96020776  total=4  flagged=4
  ✓ DE102024103232A1_96431667  total=7  flagged=7
  ✓ DE102024103420A1_96431625  total=5  flagged=5
  ✓ DE102024104137A1_96499238  total=5  flagged=5
  ✓ DE102024104138A1_96499224  total=5  flagged=5
  ✓ DE102024105430A1_96659127  total=2  flagged=2
  ✓ DE102024105438A1_96659019  total=3  flagged=3
  ✓ DE102024105439A1_96659041  total=5  flagged=5
  ✓ DE102024105440A1_96659522  total=3  flagged=3
  ✓ DE102024105441A1_96659189  total=2  flagged=2
  ✓ DE102024105446A1_96658943  total=3  flagged=3
  ✓ DE102024105448A1_96659245  total=2  flagged=2
  ✓ DE102024105449A1_96659500  total=4  flagged=4
  ✓ DE102024105450A1_96658937  total=4  flagged=4
  ✓ DE102024105452A1_96659133  total=5  flagged=5
  ✓ DE102024106633A1_96810519  total=9  flagged=9
  ✓ DE102024122189A1_98433859  total=11  flagged=11
  ✓ DE102024127443A1_98977501  total=3  flagged=3
  ✓ DE202008012643U1_40157972  total=3  flagged=3
  ✓ DE202013011072U1_50098871  total=1  flagged=1
  ✓ DE202013011452U1_50383557  total=3  flagged=3
  ✓ DE202014004877U1_51349878  total=3  flagged=3
  ✓ DE202015007089U1_54768325  total=1  flagged=1
  ✓ DE202016005012U1_57110400  total=1  flagged=1
  ✓ DE202018002525U1_62983090  total=6  flagged=6
  ✓ DE202018104519U1_68053281  total=6  flagged=4
  ✓ DE202018104722U1_63587890  total=1  flagged=1
  ✓ DE202019000936U1_66335505  total=3  flagged=3
  ✓ DE202019001820U1_67848556  total=2  flagged=2
  ✓ DE202019002731U1_67622690  total=7  flagged=7
  ✓ DE202020000096U1_70546105  total=1  flagged=1
  ✓ DE202020005116U1_74846132  total=5  flagged=5
  ✓ DE202023102941U1_92713002  total=11  flagged=9
  ✓ DE202024002149U1_94391509  total=8  flagged=8
  ✓ DE202024104657U1_94391467  total=4  flagged=4
  ✓ DE202024104658U1_94391535  total=3  flagged=2
  ✓ EP2570345A1_46924211  total=5  flagged=5
  ✓ EP2669195A1_48537748  total=12  flagged=12
  ✓ EP3119674A2_57588805  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ EP3290334A1_59745849  total=12  flagged=12
  ✓ EP3360780A1_61132051  total=12  flagged=10
  ✓ EP3453616A1_63293968  total=12  flagged=11
  ✓ EP3594113A1_63449420  total=10  flagged=10
  ✓ EP3636545A1_68242353  total=12  flagged=12
  ✓ EP3770063A1_67851083  total=8  flagged=8
  ✓ EP3805100A1_68242276  total=8  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ EP3907132A1_70680379  total=8  flagged=8
  ✓ EP3974315A1_72659736  total=6  flagged=6
  ✓ EP3998191A1_74672189  total=7  flagged=6
  ✓ EP3998195A1_74672222  total=5  flagged=5
  ✓ EP3998199A1_74672090  total=6  flagged=6
  ✓ EP3998206A1_74672197  total=8  flagged=8
  ✓ EP3998209A1_74859722  total=12  flagged=12
  ✓ EP4134301A1_77316847  total=6  flagged=5
  ✓ EP4151521A1_78695660  total=8  flagged=8
  ✓ EP4155193A1_77913035  total=7  flagged=6
  ✓ EP4230518A1_80445889  total=6  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ EP4303124A1_82850459  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ EP4306409A1_82594614  total=3  flagged=2

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ EP4339109A1_83593899  total=8  flagged=8
  ✓ EP4361026A1_84043779  total=7  flagged=6
  ✓ EP4417511A1_85285234  total=8  flagged=4
  ✓ EP4434880A1_85726750  total=7  flagged=7
  ✓ EP4467450A1_87196346  total=13  flagged=13
  ✓ EP4506770A1_87567469  total=12  flagged=8
  ✓ EP4545416A1_88511180  total=6  flagged=5
  ✓ EP4559808A1_88923633  total=6  flagged=6
  ✓ EP4563464A1_93741590  total=13  flagged=12
  ✓ EP4653315A1_91924121  total=11  flagged=11
  ✓ EP4653316A1_91924208  total=11  flagged=11
  ✓ EP4717605A1_90363660  total=9  flagged=8
  ✓ EP4741286A1_93455580  total=8  flagged=8
  ✓ EP4748710A1_94476356  total=10  flagged=10
  ✓ EP4748711A1_94383019  total=12  flagged=12
  ✓ EP4749890A1_97563936  total=12  flagged=12
  ✓ ES1291103U_81706521  total=2  flagged=2
  ✓ ES2288083A1_38787093  total=8  flagged=8
  ✓ ES2289903A1_38961544  total=2  flagged=2
  ✓ ES2317764A1_40513476  total=1  flagged=1
  ✓ ES2349098A1_43415152  total=4  flagged=4
  ✓ ES2555162A1_54883777  total=1  flagged=1
  ✓ ES2604711A1_58191740  total=1  flagged=1
  ✓ ES2775773A1_71729122  total=12  flagged=12
  ✓ FR2830237A1_8867702  total=3  flagged=2
  ✓ FR2942455A1_42557021  total=5  flagged=4
  ✓ FR2955559A1_42651204  total=6  flagged=6
  ✓ FR2980171A1_45757474  total=12  flagged=12
  ✓ FR2993245A1_46940535  total=1  flagged=1
  ✓ FR2997924A1_47741044  total=3  flagged=3
  ✓ FR3018768A1_50829035  total=5  flagged=5
  ✓ FR3033363A1_53404613  total=4  flagged=4
  ✓ FR3037038A1_54545172  total=2  flagged=2
  ✓ FR3041930A1_55361533  total=3  flagged=3
  ✓ FR3071480A1_65859711  total=11  flagged=10
  ✓ FR3074779A1_61028020  total=5  flagged=5
  ✓ FR3092083A1_67185245  total=2  flagged=2
  ✓ FR3096959A1_68343003  total=2  flagged=2
  ✓ FR3101328A1_69375455  total=2  flagged=2
  ✓ FR3104333A1_69903398  total=2  flagged=2
  ✓ FR3106572A1_69811406  total=5  flagged=5
  ✓ FR3111872A1_74095847  total=2  flagged=2
  ✓ FR3115264A1_74347237  total=2  flagged=2
  ✓ FR3115265A1_74347238  total=2  flagged=2
  ✓ FR3115266A1_74592074  total=2  flagged=2
  ✓ FR3119159A1_75690391  total=2  flagged=2
  ✓ FR3127478A1_80225585  total=2  flagged=2
  ✓ FR3136745A1_83996810  total=2  flagged=2
  ✓ FR3143549A1_86007682  total=2  flagged=2
  ✓ FR3146308A1_87280542  total=2  flagged=2
  ✓ FR3158709A1_91247625  total=2  flagged=2
  ✓ FR3159149A1_91335035  total=2  flagged=2
  ✓ GB201303910D0_48142435  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ GB201307739D0_48627027  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ GB201307770D0_48627052  total=4  flagged=4
  ✓ GB201502495D0_52781619  total=3  flagged=3
  ✓ GB201721835D0_61131560  total=9  flagged=9
  ✓ GB201721837D0_61131622  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ GB201801059D0_61283657  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ GB201801766D0_61730906  total=4  flagged=1
  ✓ GB201806772D0_62236143  total=7  flagged=7
  ✓ GB201903200D0_66380275  total=5  flagged=5
  ✓ GB202006780D0_71134956  total=6  flagged=6
  ✓ GB202006781D0_71134839  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ GB202210440D0_84540139  total=12  flagged=12
  ✓ GB202302628D0_85793928  total=12  flagged=11
  ✓ GB202302720D0_85793925  total=11  flagged=11
  ✓ GB202306162D0_86605496  total=8  flagged=6
  ✓ GB202311251D0_87852126  total=8  flagged=7
  ✓ GB202313751D0_88412872  total=12  flagged=12
  ✓ GB202313753D0_88412696  total=12  flagged=12
  ✓ GB202410204D0_92458746  total=3  flagged=3
  ✓ GB202410221D0_92458823  total=12  flagged=12
  ✓ GB202415968D0_93743348  total=12  flagged=12
  ✓ IN202011031027A_72202011031027  total=5  flagged=5
  ✓ IT201900011040A1_68501895  total=6  flagged=6
  ✓ IT202100023033A1_78649894  total=7  flagged=7
  ✓ IT202200018594A1_84359689  total=9  flagged=9
  ✓ IT202300024612A1_89897947  total=3  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ ITPI20130073A1_49519050  total=7  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ ITTO20130495A1_49085162  total=7  flagged=6
  ✓ ITUB20150829A1_53901004  total=11  flagged=10
  ✓ JP2014213846A_51940008  total=3  flagged=3
  ✓ JP2023526056A_60002023526056  total=12  flagged=12
  ✓ JP2024519073A_60002024519073  total=12  flagged=12
  ✓ JP7438589B1_90011450  total=8  flagged=8
  ✓ KR100555176B1_37179218  total=12  flagged=12
  ✓ KR100822366B1_39571552  total=11  flagged=11
  ✓ KR100832067B1_39665122  total=3  flagged=3
  ✓ KR101129249B1_46607088  total=7  flagged=7
  ✓ KR101749863B1_59282852  total=7  flagged=7
  ✓ KR101813681B1_61070316  total=11  flagged=11
  ✓ KR102164227B1_72886441  total=12  flagged=12
  ✓ KR102211475B1_74559535  total=10  flagged=10
  ✓ KR102622742B1_89533015  total=12  flagged=12
  ✓ KR102712524B1_93117104  total=10  flagged=10
  ✓ KR102760903B1_94612113  total=9  flagged=9
  ✓ KR20050016643A_41783551  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ KR20060074923A_37167543  total=1  flagged=1
  ✓ KR20060079414A_37171053  total=4  flagged=4
  ✓ KR20060094937A_37602565  total=12  flagged=12
  ✓ KR20100094056A_42758287  total=5  flagged=5
  ✓ KR20110127560A_45396178  total=6  flagged=6
  ✓ KR20130031490A_48180625  total=11  flagged=11
  ✓ KR20130083961A_48994747  total=12  flagged=12
  ✓ KR20160031602A_55645015  total=6  flagged=6
  ✓ KR20160120094A_57250409  total=6  flagged=6
  ✓ KR20170030407A_58502248  total=7  flagged=7
  ✓ KR20190059174A_66675876  total=8  flagged=8
  ✓ KR20190119712A_68460770  total=9  flagged=9
  ✓ KR20200079649A_71571440  total=12  flagged=9
  ✓ KR20210059370A_76145537  total=8  flagged=8
  ✓ KR20220017042A_80266315  total=12  flagged=12
  ✓ KR20220033079A_80937728  total=12  flagged=12
  ✓ KR20230075012A_86542877  total=6  flagged=6
  ✓ KR20230089903A_86989656  total=11  flagged=11
  ✓ KR20240080620A_91480079  total=4  flagged=4
  ✓ KR20240170008A_93847180  total=12  flagged=12
  ✓ KR20250038333A_95205843  total=11  flagged=11
  ✓ KR20250121294A_96733921  total=12  flagged=12
  ✓ KR20260072583A_84020260072583  total=41  flagged=40

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ NL2019667B1_64661429  total=9  flagged=9
  ✓ PT109064A_59579337  total=11  flagged=10
  ✓ RO131684A0_58093839  total=6  flagged=6
  ✓ RU180474U1_62619630  total=7  flagged=7
  ✓ RU189830U1_66792710  total=5  flagged=5
  ✓ RU192967U1_68162677  total=3  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ RU2015128842A_57758323  total=4  flagged=4
  ✓ RU2015135410A_58453840  total=6  flagged=6
  ✓ RU2018102765A_67513055  total=8  flagged=8
  ✓ RU2018115530A_68500204  total=12  flagged=12
  ✓ RU2018121419A_68834286  total=4  flagged=4
  ✓ RU2018140767A_70734813  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ RU2577931C1_55648085  total=2  flagged=2
  ✓ RU2641952C1_61023785  total=3  flagged=3
  ✓ RU2657650C1_62620090  total=7  flagged=7
  ✓ RU2670361C1_63923480  total=10  flagged=10
  ✓ RU2681464C1_65632802  total=5  flagged=4
  ✓ RU2698276C1_67733939  total=5  flagged=5
  ✓ RU2700154C1_67989562  total=6  flagged=6
  ✓ RU2701284C1_68063557  total=5  flagged=5
  ✓ RU2711768C1_69184024  total=4  flagged=4
  ✓ RU2725833C1_71510455  total=4  flagged=4
  ✓ RU2727787C1_71741321  total=4  flagged=2
  ✓ RU2729750C1_72086323  total=1  flagged=1
  ✓ RU2730745C1_72238031  total=10  flagged=10
  ✓ RU2755561C1_77745520  total=9  flagged=8
  ✓ RU2757693C1_78286650  total=12  flagged=12
  ✓ RU2759060C1_78466873  total=4  flagged=4
  ✓ RU2759061C1_78466891  total=9  flagged=9
  ✓ RU2762441C1_80039043  total=8  flagged=8
  ✓ RU2762906C1_80039133  total=4  flagged=4
  ✓ RU2764311C1_80040360  total=6  flagged=4
  ✓ SK500442018A3_68393052  total=6  flagged=6
  ✓ TWI627104B_62386186  total=12  flagged=8
  ✓ UA124132C2_76865258  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ UA151311U_82404778  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ UA152017U_89902489  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10017247B1_62750261  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10053213B1_62142993  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10144503B1_64451753  total=12  flagged=12
  ✓ US10167076B1_64736539  total=7  flagged=7
  ✓ US10301008B1_66636453  total=5  flagged=5
  ✓ US10418868B1_67908946  total=8  flagged=8
  ✓ US10421540B1_60001758  total=7  flagged=7
  ✓ US10435145B1_68108710  total=12  flagged=12
  ✓ US10444093B1_68165195  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10450062B1_68242128  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10450063B1_68242087  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10479482B1_68536356  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10501173B1_68766061  total=5  flagged=5
  ✓ US10526079B1_69058765  total=9  flagged=9
  ✓ US10562608B1_69528282  total=10  flagged=10
  ✓ US10589838B1_69779009  total=10  flagged=10
  ✓ US10913529B1_74537066  total=12  flagged=12
  ✓ US11001377B1_75846002  total=9  flagged=9
  ✓ US11072423B1_76971454  total=12  flagged=12
  ✓ US11077937B1_77063283  total=12  flagged=10
  ✓ US11124286B1_77749153  total=12  flagged=12
  ✓ US11208206B1_79168222  total=8  flagged=8
  ✓ US11319064B1_81380637  total=12  flagged=12
  ✓ US11449078B1_83286317  total=8  flagged=8
  ✓ US11465737B1_83547212  total=12  flagged=12
  ✓ US11472538B1_83603712  total=6  flagged=6
  ✓ US11485488B1_83809387  total=12  flagged=12
  ✓ US11548621B1_84810682  total=11  flagged=11
  ✓ US11643196B1_86242413  total=6  flagged=5
  ✓ US11673662B1_86701325  total=12  flagged=11
  ✓ US11688723B1_86899026  total=12  flagged=12
  ✓ US11691709B1_86993171  total=12  flagged=11
  ✓ US11691744B1_86993180  total=6  flagged=5
  ✓ US11697495B1_87070627  total=9  flagged=9
  ✓ US11745890B1_87882406  total=9  flagged=9
  ✓ US11772788B1_88196009  total=12  flagged=12
  ✓ US11780576B1_88242423  total=12  flagged=12
  ✓ US11787551B1_88309302  total=12  flagged=12
  ✓ US11807382B1_88649710  total=8  flagged=8
  ✓ US11811276B1_88649937  total=12  flagged=12
  ✓ US12006989B1_91382768  total=11  flagged=10
  ✓ US12091167B1_92716119  total=12  flagged=12
  ✓ US12202600B1_94282923  total=12  flagged=9
  ✓ US12227299B1_94610740  total=12  flagged=12
  ✓ US12291327B1_95563743  total=11  flagged=11
  ✓ US12312080B1_95823600  total=4  flagged=4
  ✓ US12325540B1_89898199  total=10  flagged=8
  ✓ US12377973B1_96587791  total=9  flagged=8
  ✓ US12420923B1_93314042  total=12  flagged=12
  ✓ US12486026B1_97879582  total=7  flagged=7
  ✓ US12503223B1_98223577  total=10  flagged=10
  ✓ US12559227B1_98829969  total=12  flagged=11
  ✓ US12570400B1_99012509  total=12  flagged=9
  ✓ US12600459B1_99440105  total=12  flagged=10
  ✓ US2002100834A1_26951040  total=12  flagged=12
  ✓ US2002100835A1_3827470  total=12  flagged=12
  ✓ US2002154996A1_26705128  total=12  flagged=12
  ✓ US2003085319A1_27493969  total=12  flagged=12
  ✓ US2004025490A1_31499647  total=12  flagged=12
  ✓ US2004026563A1_33563608  total=12  flagged=11
  ✓ US2004069901A1_22756957  total=12  flagged=12
  ✓ US2004129833A1_11459538  total=7  flagged=7
  ✓ US2004155143A1_23135826  total=12  flagged=12
  ✓ US2004232279A1_33450313  total=9  flagged=9
  ✓ US2005017127A1_34079630  total=11  flagged=11
  ✓ US2005061910A1_27762744  total=3  flagged=3
  ✓ US2005127238A1_34657098  total=9  flagged=9
  ✓ US2005178879A1_34837757  total=4  flagged=4
  ✓ US2005223694A1_27665376  total=5  flagged=5
  ✓ US2005230519A1_35095296  total=6  flagged=6
  ✓ US2005230520A1_3836862  total=11  flagged=11
  ✓ US2006016929A1_35656111  total=6  flagged=6
  ✓ US2006038061A1_36148747  total=12  flagged=12
  ✓ US2006054736A1_36969823  total=9  flagged=9
  ✓ US2006113426A1_31495862  total=12  flagged=12
  ✓ US2006151666A1_36652344  total=11  flagged=11
  ✓ US2006192046A1_36141977  total=7  flagged=7
  ✓ US2006192047A1_36710041  total=12  flagged=12
  ✓ US2006198732A1_33154123  total=3  flagged=3
  ✓ US2006202081A1_46322670  total=12  flagged=12
  ✓ US2006239824A1_32823163  total=7  flagged=7
  ✓ US2007158494A1_31503581  total=12  flagged=12
  ✓ US2007205326A1_39402160  total=4  flagged=4
  ✓ US2007221779A1_34909592  total=12  flagged=12
  ✓ US2008054121A1_39150154  total=12  flagged=12
  ✓ US2008169375A1_37053048  total=12  flagged=11
  ✓ US2008173769A1_39640291  total=5  flagged=5
  ✓ US2008240920A1_33535776  total=5  flagged=5
  ✓ US2008243313A1_39713981  total=5  flagged=5
  ✓ US2008272226A1_39540404  total=7  flagged=7
  ✓ US2008283673A1_36647872  total=12  flagged=12
  ✓ US2008292468A1_38256747  total=12  flagged=12
  ✓ US2009008499A1_40075709  total=11  flagged=11
  ✓ US2009008510A1_38037471  total=7  flagged=7
  ✓ US2009016877A1_39595972  total=11  flagged=11
  ✓ US2009084890A1_38191853  total=5  flagged=5
  ✓ US2009127379A1_36647957  total=10  flagged=10
  ✓ US2009140095A1_40674737  total=4  flagged=4
  ✓ US2009212166A1_39787926  total=7  flagged=7
  ✓ US2009218438A1_31991310  total=9  flagged=9
  ✓ US2009224096A1_41052615  total=9  flagged=9
  ✓ US2009256026A1_41162269  total=6  flagged=6
  ✓ US2009261209A1_38269095  total=12  flagged=12
  ✓ US2009266941A1_41214046  total=5  flagged=5
  ✓ US2009266942A1_39645003  total=4  flagged=4
  ✓ US2009283644A1_39855065  total=4  flagged=4
  ✓ US2010001143A1_41463611  total=8  flagged=8
  ✓ US2010051740A1_41723862  total=12  flagged=12
  ✓ US2010051753A1_39468355  total=12  flagged=12
  ✓ US2010072325A1_42036641  total=5  flagged=5
  ✓ US2010171001A1_42198440  total=8  flagged=8
  ✓ US2010264256A1_42980278  total=12  flagged=12
  ✓ US2010270419A1_40795959  total=12  flagged=12
  ✓ US2010270435A1_39609176  total=3  flagged=3
  ✓ US2010276549A1_39788775  total=4  flagged=4
  ✓ US2010301158A1_40886371  total=2  flagged=2
  ✓ US2011001001A1_40913336  total=12  flagged=12
  ✓ US2011001020A1_43412095  total=5  flagged=5
  ✓ US2011024552A1_43526078  total=5  flagged=4
  ✓ US2011031355A1_43534097  total=8  flagged=7
  ✓ US2011042510A1_43604537  total=12  flagged=12
  ✓ US2011163199A1_39637816  total=12  flagged=12
  ✓ US2011168835A1_44257785  total=6  flagged=6
  ✓ US2011194934A1_44356238  total=12  flagged=12
  ✓ US2011217163A1_44531481  total=9  flagged=9
  ✓ US2011259687A1_42269088  total=9  flagged=9
  ✓ US2011303795A1_56291239  total=7  flagged=7
  ✓ US2011315809A1_47883631  total=12  flagged=12
  ✓ US2012012692A1_45497427  total=8  flagged=8
  ✓ US2012049009A1_45695835  total=12  flagged=12
  ✓ US2012056040A1_40639929  total=12  flagged=12
  ✓ US2012061509A1_43126417  total=5  flagged=5
  ✓ US2012061526A1_43126416  total=4  flagged=3
  ✓ US2012063897A1_43126414  total=5  flagged=5
  ✓ US2012091257A1_42263722  total=10  flagged=9
  ✓ US2012119016A1_46046924  total=12  flagged=12
  ✓ US2012199699A1_45558617  total=11  flagged=11
  ✓ US2012211608A1_42077515  total=7  flagged=7
  ✓ US2012234968A1_46827703  total=10  flagged=9
  ✓ US2012261523A1_47005722  total=12  flagged=11
  ✓ US2012298789A1_45773779  total=9  flagged=9
  ✓ US2012318908A1_47352908  total=4  flagged=4
  ✓ US2013020429A1_47555117  total=7  flagged=6
  ✓ US2013026302A1_46142159  total=4  flagged=4
  ✓ US2013026303A1_45063079  total=11  flagged=10
  ✓ US2013026304A1_45092316  total=11  flagged=10
  ✓ US2013026305A1_44925466  total=12  flagged=11
  ✓ US2013035808A1_44196181  total=5  flagged=4
  ✓ US2013082135A1_46801287  total=1  flagged=1
  ✓ US2013092799A1_48140344  total=9  flagged=6
  ✓ US2013099065A1_44541344  total=7  flagged=7
  ✓ US2013112804A1_44904126  total=12  flagged=11
  ✓ US2013118856A1_48279558  total=5  flagged=5
  ✓ US2013121827A1_45400986  total=7  flagged=7
  ✓ US2013140405A1_48523311  total=11  flagged=11
  ✓ US2013149151A1_45444559  total=12  flagged=11
  ✓ US2013164129A1_45811330  total=8  flagged=8
  ✓ US2013264429A1_46000207  total=7  flagged=4
  ✓ US2013306802A1_48430087  total=12  flagged=12
  ✓ US2014008498A1_44800986  total=7  flagged=7
  ✓ US2014084114A1_50337921  total=11  flagged=11
  ✓ US2014110533A1_47424268  total=12  flagged=12
  ✓ US2014124613A1_45690046  total=12  flagged=12
  ✓ US2014138477A1_48781750  total=9  flagged=9
  ✓ US2014158815A1_50879887  total=12  flagged=11
  ✓ US2014158816A1_50879888  total=12  flagged=8
  ✓ US2014175214A1_50973533  total=12  flagged=12
  ✓ US2014263822A1_51523277  total=3  flagged=3
  ✓ US2014263854A1_48444095  total=12  flagged=12
  ✓ US2014263855A1_48444096  total=9  flagged=9
  ✓ US2014271180A1_48444262  total=11  flagged=11
  ✓ US2014321968A1_48741027  total=6  flagged=6
  ✓ US2014339354A1_51895012  total=11  flagged=11
  ✓ US2014360830A1_52009426  total=12  flagged=12
  ✓ US2015014475A1_52276366  total=12  flagged=11
  ✓ US2015028151A1_52389667  total=12  flagged=8
  ✓ US2015028155A1_45930023  total=5  flagged=5
  ✓ US2015048213A1_50349532  total=12  flagged=12
  ✓ US2015053826A1_49161167  total=9  flagged=9
  ✓ US2015166175A1_50478459  total=5  flagged=5
  ✓ US2015175260A1_49080841  total=7  flagged=5
  ✓ US2015191243A1_49916084  total=12  flagged=12
  ✓ US2015197337A1_51261881  total=12  flagged=12
  ✓ US2015225079A1_53774285  total=12  flagged=12
  ✓ US2015251749A1_54016621  total=5  flagged=5
  ✓ US2015266571A1_54141359  total=12  flagged=11
  ✓ US2015274290A1_54189271  total=11  flagged=10
  ✓ US2015284079A1_54209073  total=10  flagged=10
  ✓ US2015295105A1_47002500  total=10  flagged=10
  ✓ US2015314865A1_48237003  total=7  flagged=6
  ✓ US2015344134A1_54700893  total=12  flagged=11
  ✓ US2015360774A1_54835505  total=12  flagged=12
  ✓ US2015361923A1_47758026  total=12  flagged=12
  ✓ US2015375860A1_54929679  total=10  flagged=10
  ✓ US2016009376A1_55067013  total=5  flagged=5
  ✓ US2016009387A1_55067015  total=7  flagged=7
  ✓ US2016023754A1_54866841  total=12  flagged=12
  ✓ US2016026190A1_55166717  total=9  flagged=9
  ✓ US2016031555A1_54145473  total=12  flagged=12
  ✓ US2016031556A1_55179237  total=12  flagged=12
  ✓ US2016083060A1_54545564  total=12  flagged=12
  ✓ US2016096613A1_55632264  total=5  flagged=3
  ✓ US2016101854A1_52392625  total=4  flagged=4
  ✓ US2016114885A1_51898467  total=10  flagged=10
  ✓ US2016137298A1_55961005  total=12  flagged=12
  ✓ US2016144957A1_56009443  total=12  flagged=12
  ✓ US2016159458A1_55077616  total=4  flagged=4
  ✓ US2016159468A1_54703900  total=12  flagged=12
  ✓ US2016167780A1_49182418  total=10  flagged=7
  ✓ US2016200434A1_55070897  total=9  flagged=9
  ✓ US2016200436A1_56366982  total=12  flagged=11
  ✓ US2016207624A1_56407247  total=9  flagged=6
  ✓ US2016207625A1_51422096  total=12  flagged=12
  ✓ US2016214710A1_55218435  total=12  flagged=10
  ✓ US2016229531A1_56566535  total=12  flagged=12
  ✓ US2016236774A1_55168123  total=5  flagged=5
  ✓ US2016236775A1_56620788  total=8  flagged=8
  ✓ US2016244158A1_56690227  total=8  flagged=8
  ✓ US2016280369A1_53003021  total=8  flagged=8
  ✓ US2016288903A1_57015698  total=9  flagged=9
  ✓ US2016304194A1_57128418  total=11  flagged=11
  ✓ US2016304195A1_57129607  total=12  flagged=12
  ✓ US2016311522A1_57110590  total=12  flagged=12
  ✓ US2016311529A1_50071007  total=7  flagged=7
  ✓ US2016311545A1_57147406  total=8  flagged=8
  ✓ US2016325821A1_55968929  total=12  flagged=9
  ✓ US2016340038A1_57324322  total=12  flagged=12
  ✓ US2016347443A1_53479161  total=11  flagged=11
  ✓ US2016347447A1_56072277  total=6  flagged=6
  ✓ US2016347448A1_57396965  total=11  flagged=11
  ✓ US2016368600A1_57587574  total=12  flagged=12
  ✓ US2016368601A1_57587636  total=11  flagged=11
  ✓ US2017001721A1_57682863  total=11  flagged=11
  ✓ US2017057630A1_52472335  total=7  flagged=7
  ✓ US2017081037A1_56979435  total=7  flagged=7
  ✓ US2017101176A1_58498735  total=6  flagged=3
  ✓ US2017113795A1_58562387  total=4  flagged=4
  ✓ US2017121029A1_58634297  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017133771A1_53097343  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017144746A1_58719945  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017158323A1_58799672  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017159674A1_57280947  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017166302A1_59018898  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017174335A1_50737560  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017183088A1_55310758  total=3  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017183090A1_54332888  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017183091A1_59086872  total=5  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017203839A1_57910169  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017217585A1_51795710  total=8  flagged=8
  ✓ US2017225779A1_58043895  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017240273A1_20002017240273  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017259911A1_59788458  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017274993A1_59896532  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017283052A1_59958557  total=9  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017297685A1_60041236  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017297699A1_60039988  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017305566A1_60088903  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017305567A1_60088387  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017305568A1_60088816  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017313410A1_60158095  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017320567A1_60242907  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017320568A1_55760329  total=3  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017334557A1_56285137  total=5  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017336809A1_55954925  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017341733A1_60421112  total=6  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017341740A1_60412945  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018001945A1_60806489  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018002003A1_60477933  total=10  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018002009A1_60806086  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018002011A1_56801439  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018002012A1_60806496  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018002013A1_60806497  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018002014A1_60806574  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018002016A1_60806501  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018002026A1_59269890  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018022467A1_56406210  total=8  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018029703A1_53491619  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018029704A1_56355571  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018037319A1_56692622  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018043986A1_59295123  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018044011A1_61160888  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018044012A1_61160076  total=12  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018050792A1_61190658  total=9  flagged=9
  ✓ US2018057148A1_61241613  total=9  flagged=9
  ✓ US2018057155A1_61241550  total=8  flagged=8
  ✓ US2018057159A1_61240363  total=9  flagged=9
  ✓ US2018057160A1_61241488  total=12  flagged=12
  ✓ US2018057161A1_58448450  total=8  flagged=8
  ✓ US2018057162A1_58448451  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018079485A1_61617796  total=8  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018079486A1_61617823  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018079487A1_61617830  total=10  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018079493A1_59914391  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018079499A1_57460451  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018079500A1_61617432  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018079501A1_61617433  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018079502A1_61617921  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018079503A1_57609789  total=12  flagged=12
  ✓ US2018086442A1_55440457  total=7  flagged=7
  ✓ US2018086445A1_61687874  total=5  flagged=5
  ✓ US2018086448A1_61687467  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018099738A1_61830468  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018105267A1_61902127  total=6  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018105279A1_61903080  total=6  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018118335A1_60021963  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018141647A1_57319630  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018141652A1_55345846  total=3  flagged=1

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018141653A1_62144754  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018148160A1_62193487  total=10  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018155016A1_57833760  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018155017A1_62240752  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018162525A1_62487747  total=12  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018163795A1_60582510  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018170517A1_62556699  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018178899A1_62625439  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018178907A1_57774507  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018178910A1_62700616  total=12  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018186445A1_62709227  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018186449A1_62709286  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018201369A1_62839037  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018208296A1_58159046  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018208305A1_62905591  total=10  flagged=10
  ✓ US2018215465A1_62977577  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018222579A1_55025148  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018222580A1_63038676  total=12  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018229606A1_61189299  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018229830A1_63105813  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018237136A1_60674042  total=12  flagged=12
  ✓ US2018244367A1_58410234  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018251227A1_60162059  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018252263A1_60162060  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018252264A1_60153222  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018265189A1_58401526  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018281953A1_63672934  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018290735A1_63710237  total=3  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018290736A1_63169582  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018297697A1_59685458  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018297711A1_63791514  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018297712A1_63791504  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018305005A1_63853079  total=12  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018312246A1_56193192  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018312251A1_63915910  total=12  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018327086A1_64097616  total=9  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018334240A1_64269913  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018334241A1_64269977  total=9  flagged=9
  ✓ US2018339761A1_64400554  total=12  flagged=12
  ✓ US2018339762A1_60702355  total=8  flagged=8
  ✓ US2018339769A1_64400489  total=5  flagged=5
  ✓ US2018339771A1_64400208  total=5  flagged=5
  ✓ US2018339772A1_64400397  total=12  flagged=11
  ✓ US2018339773A1_64400494  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018346108A1_64459164  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018346111A1_64456259  total=9  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018346112A1_64458704  total=11  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018346113A1_61690895  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018354607A1_64562521  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018354613A1_59030886  total=5  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018354614A1_59901057  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018354615A1_61972363  total=12  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018354616A1_64562549  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018362155A1_64657086  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018362160A1_59581760  total=9  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018362180A1_62636049  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018370624A1_56284961  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018370625A1_59789030  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018370626A1_60326372  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2018370629A1_64691393  total=7  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019002078A1_61972364  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019009895A1_64104960  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019009898A1_64904449  total=12  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019023385A1_65014799  total=8  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019023391A1_63035884  total=9  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019023393A1_57850811  total=6  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019031318A1_63077742  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019031331A1_65138625  total=12  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019031333A1_62985913  total=10  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019031334A1_65138632  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019031336A1_65138209  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019031337A1_65138610  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019031338A1_65138134  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019031339A1_65138108  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019031361A1_65137870  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019039718A1_59974273  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019048904A1_65272662  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019061901A1_65434642  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019061932A1_65434805  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019061936A1_65434861  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019063574A1_59311449  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019071174A1_56084216  total=12  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019084684A1_65719885  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019092461A1_63556245  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019092485A1_65808311  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019100297A1_63667701  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019100303A1_63667703  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019100313A1_63667704  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019100322A1_60186065  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019106197A1_65993818  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019112028A1_66095558  total=9  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019112039A1_60302055  total=12  flagged=12
  ✓ US2019118942A1_60954978  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019127060A1_63915098  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019127063A1_59270091  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019135413A1_66326792  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019135420A1_66326819  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019135423A1_63965440  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019135424A1_64332206  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019135426A1_60785698  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019135427A1_66328276  total=11  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019144100A1_66433028  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019144107A1_60953748  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019144108A1_66431183  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019144109A1_63667702  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019144126A1_60629569  total=7  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019152593A1_58643397  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019154106A1_66532222  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019161188A1_56263910  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019168866A1_59632714  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019176981A1_66735121  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019185141A1_66815605  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019185142A1_66815566  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019185150A1_66815629  total=8  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019185151A1_66814180  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019185152A1_66815611  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019185153A1_66814181  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019225321A1_67299747  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019233098A1_67391875  total=12  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019256190A1_67617194  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019256200A1_67617504  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019263515A1_67685511  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019270517A1_57963678  total=10  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019271398A1_67768019  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019276142A1_67844398  total=8  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019277353A1_63667705  total=8  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019283858A1_67903817  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019291861A1_67984023  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019291863A1_60325626  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019300152A1_68054797  total=12  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019300166A1_68054806  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019301486A1_68055853  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019308723A1_68097883  total=4  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019308738A1_62748876  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019310660A1_68097142  total=4  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019315448A1_65817915  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019322365A1_68237398  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019322366A1_68236244  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019322368A1_68237434  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019323563A1_68237553  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019329866A1_68292032  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019329880A1_68292158  total=2  flagged=1

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019329882A1_66857992  total=12  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019329898A1_68292112  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019332126A1_68292145  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019337606A1_68384472  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019337612A1_68384482  total=8  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019337614A1_68384483  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019337615A1_59759868  total=6  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019338810A1_68383740  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019340933A1_68385027  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019340934A1_68385033  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019344877A1_68463902  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019375497A1_66091988  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019382100A1_68839131  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019382106A1_68840675  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019389568A1_63047276  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019389571A1_66397152  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2019389572A1_68981372  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020001987A1_60478953  total=12  flagged=12
  ✓ US2020009989A1_67540159  total=6  flagged=6
  ✓ US2020010185A1_67540160  total=5  flagged=5
  ✓ US2020010186A1_67540162  total=7  flagged=7
  ✓ US2020010187A1_68697150  total=12  flagged=12
  ✓ US2020010188A1_67539988  total=7  flagged=7
  ✓ US2020010210A1_68943498  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020023959A1_67438519  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020023963A1_67003280  total=6  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020031464A1_63448384  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020031488A1_69179019  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020039633A1_69227888  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020055586A1_69524485  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020055595A1_63170062  total=12  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020062139A1_67540105  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020062374A1_69584302  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020062383A1_69584309  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020062384A1_69584235  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020079501A1_67928706  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020079503A1_69720448  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020086971A1_65818387  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020089227A1_69773972  total=12  flagged=12
  ✓ US2020102068A1_64274646  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020115035A1_65411791  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020115036A1_70159808  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020115045A1_65861307  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020140073A1_68583552  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020140078A1_70458268  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020140079A1_68424823  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020140080A1_70460284  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020148345A1_68581336  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020148347A1_68466810  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020148354A1_70526762  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020156778A1_70727181  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020164975A1_67953694  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020164976A1_64742606  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020172235A1_68296323  total=5  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020180756A1_56410734  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020193847A1_71072724  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020207467A1_64901922  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020207468A1_71123692  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020223532A1_71517180  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020223533A1_71517369  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020223537A1_69137756  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020223542A1_65809451  total=12  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020231293A1_71609657  total=6  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020239127A1_70611188  total=11  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020239134A1_71732200  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020247525A1_66287149  total=2  flagged=2

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020247536A1_68886875  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020255128A1_71944769  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020262553A1_72041276  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020269975A1_66102627  total=10  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020269980A1_66529948  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020272141A1_72141772  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020301446A1_72200016  total=10  flagged=10

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020307767A1_72607182  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020307773A1_72607727  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020317332A1_65036830  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020324886A1_70227835  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020331585A1_72832843  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020331601A1_57910091  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020331602A1_70973832  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020333779A1_63448347  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020354048A1_70616987  total=8  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020354050A1_64753382  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020354052A1_72943525  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020354054A1_61283487  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020361601A1_73228294  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020361622A1_68426170  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2020369363A1_73053049  total=6  flagged=5
  ✓ US2020385130A1_73651130  total=9  flagged=9
  ✓ US2020385139A1_73651104  total=12  flagged=12
  ✓ US2020391858A1_73746448  total=6  flagged=6
  ✓ US2020391859A1_73744870  total=9  flagged=9
  ✓ US2020391861A1_73744878  total=7  flagged=6
  ✓ US2020391862A1_73744872  total=7  flagged=6
  ✓ US2020391863A1_67143687  total=12  flagged=12
  ✓ US2020391879A1_73744885  total=8  flagged=8
  ✓ US2020398977A1_74038480  total=12  flagged=10
  ✓ US2020398980A1_68581889  total=7  flagged=7
  ✓ US2020398981A1_70969594  total=7  flagged=7
  ✓ US2020407055A1_67105910  total=6  flagged=3
  ✓ US2021001979A1_73458667  total=12  flagged=12
  ✓ US2021016876A1_71409163  total=12  flagged=12
  ✓ US2021016877A1_65685360  total=5  flagged=5
  ✓ US2021024213A1_74187458  total=7  flagged=7
  ✓ US2021031910A1_71401626  total=12  flagged=12
  ✓ US2021031911A1_74259060  total=12  flagged=12
  ✓ US2021039776A1_68062624  total=12  flagged=12
  ✓ US2021047029A1_74567111  total=12  flagged=11
  ✓ US2021053670A1_74647255  total=12  flagged=12
  ✓ US2021053672A1_62046841  total=12  flagged=12
  ✓ US2021061456A1_67070894  total=12  flagged=12
  ✓ US2021061459A1_67301171  total=12  flagged=12
  ✓ US2021064062A1_68539932  total=12  flagged=12
  ✓ US2021070429A1_68062536  total=12  flagged=12
  ✓ US2021070461A1_74850772  total=12  flagged=12
  ✓ US2021078701A1_74868309  total=10  flagged=9
  ✓ US2021086893A1_65858558  total=6  flagged=6
  ✓ US2021086897A1_74880080  total=8  flagged=8
  ✓ US2021094674A1_72050772  total=8  flagged=7
  ✓ US2021101675A1_68982861  total=6  flagged=6
  ✓ US2021101677A1_75273934  total=12  flagged=12
  ✓ US2021103298A1_75274827  total=12  flagged=12
  ✓ US2021107624A1_75383510  total=12  flagged=12
  ✓ US2021107638A1_75382535  total=12  flagged=12
  ✓ US2021107639A1_68240359  total=12  flagged=12
  ✓ US2021107640A1_72266859  total=12  flagged=12
  ✓ US2021107652A1_72944246  total=12  flagged=12
  ✓ US2021107665A1_75382541  total=12  flagged=12
  ✓ US2021114720A1_75491813  total=6  flagged=6
  ✓ US2021114723A1_75491815  total=12  flagged=12
  ✓ US2021122465A1_69172015  total=8  flagged=5
  ✓ US2021122466A1_75586565  total=12  flagged=12
  ✓ US2021122468A1_75584655  total=12  flagged=12
  ✓ US2021129985A1_62454743  total=10  flagged=10
  ✓ US2021139130A1_75846353  total=12  flagged=12
  ✓ US2021139157A1_72801358  total=9  flagged=9
  ✓ US2021163128A1_76091942  total=7  flagged=7
  ✓ US2021171188A1_60782121  total=12  flagged=12
  ✓ US2021188427A1_69414648  total=9  flagged=9
  ✓ US2021197953A1_76545896  total=9  flagged=9
  ✓ US2021197964A1_76545929  total=9  flagged=9
  ✓ US2021197965A1_62245438  total=12  flagged=11
  ✓ US2021206470A1_76654252  total=12  flagged=12
  ✓ US2021206487A1_64013129  total=5  flagged=5
  ✓ US2021215096A1_68698401  total=12  flagged=12
  ✓ US2021221527A1_76857862  total=8  flagged=8
  ✓ US2021229802A1_76971167  total=12  flagged=9
  ✓ US2021229825A1_76969716  total=10  flagged=10
  ✓ US2021245872A1_77176672  total=12  flagged=12
  ✓ US2021245873A1_77177367  total=6  flagged=6
  ✓ US2021245875A1_63259365  total=12  flagged=12
  ✓ US2021253235A1_77272059  total=12  flagged=12
  ✓ US2021253246A1_68843137  total=12  flagged=12
  ✓ US2021269148A1_77463077  total=12  flagged=12
  ✓ US2021284333A1_77664324  total=12  flagged=9
  ✓ US2021291973A1_74586890  total=12  flagged=12
  ✓ US2021293252A1_74285243  total=12  flagged=12
  ✓ US2021300527A1_77854349  total=9  flagged=9
  ✓ US2021309351A1_75339652  total=8  flagged=8
  ✓ US2021309382A1_77920732  total=6  flagged=6
  ✓ US2021316848A1_78007027  total=11  flagged=11
  ✓ US2021316849A1_78006650  total=12  flagged=11
  ✓ US2021316851A1_78006645  total=12  flagged=12
  ✓ US2021331791A1_78221760  total=12  flagged=12
  ✓ US2021331792A1_78221761  total=10  flagged=10
  ✓ US2021331794A1_78221758  total=12  flagged=11
  ✓ US2021339842A1_78292451  total=12  flagged=12
  ✓ US2021339881A1_78292538  total=12  flagged=12
  ✓ US2021339882A1_78292496  total=12  flagged=11
  ✓ US2021347472A1_78269886  total=12  flagged=10
  ✓ US2021354811A1_68691955  total=12  flagged=12
  ✓ US2021354814A1_78513792  total=12  flagged=12
  ✓ US2021354816A1_63962996  total=12  flagged=10
  ✓ US2021362836A1_78609488  total=12  flagged=12
  ✓ US2021362837A1_78609415  total=12  flagged=12
  ✓ US2021362849A1_76375653  total=10  flagged=9
  ✓ US2021362850A1_82694344  total=12  flagged=8
  ✓ US2021367465A1_71947250  total=12  flagged=12
  ✓ US2021371097A1_78706870  total=9  flagged=9
  ✓ US2021371117A1_76432483  total=5  flagged=5
  ✓ US2021380224A1_78818508  total=8  flagged=8
  ✓ US2021387724A1_78824427  total=12  flagged=12
  ✓ US2021394888A1_79023031  total=12  flagged=12
  ✓ US2021403155A1_79032375  total=8  flagged=8
  ✓ US2021403161A1_79032393  total=12  flagged=11
  ✓ US2021403173A1_74873647  total=10  flagged=10
  ✓ US2022004204A1_79167757  total=12  flagged=10
  ✓ US2022017208A1_79293273  total=12  flagged=12
  ✓ US2022017218A1_79293285  total=8  flagged=8
  ✓ US2022024569A1_79687783  total=12  flagged=12
  ✓ US2022033071A1_77103945  total=6  flagged=6
  ✓ US2022033072A1_79300326  total=4  flagged=4
  ✓ US2022043465A1_72941222  total=12  flagged=12
  ✓ US2022048639A1_71127804  total=12  flagged=12
  ✓ US2022055743A1_71126277  total=12  flagged=12
  ✓ US2022063799A1_80356275  total=12  flagged=12
  ✓ US2022063820A1_71075778  total=8  flagged=7
  ✓ US2022067616A1_80356773  total=11  flagged=11
  ✓ US2022073201A1_65440750  total=8  flagged=8
  ✓ US2022081107A1_80626189  total=6  flagged=6
  ✓ US2022081109A1_71841259  total=5  flagged=5
  ✓ US2022089276A1_71735562  total=12  flagged=12
  ✓ US2022089279A1_69159878  total=12  flagged=12
  ✓ US2022097825A1_80823366  total=12  flagged=12
  ✓ US2022097835A1_80624206  total=4  flagged=4
  ✓ US2022097836A1_80624736  total=6  flagged=6
  ✓ US2022097837A1_80823375  total=12  flagged=12
  ✓ US2022097840A1_88839988  total=10  flagged=10
  ✓ US2022111950A1_77457447  total=7  flagged=7
  ✓ US2022111953A1_77659375  total=6  flagged=6
  ✓ US2022111954A1_80818105  total=5  flagged=5
  ✓ US2022111956A1_81078840  total=12  flagged=12
  ✓ US2022119100A1_80929010  total=6  flagged=6
  ✓ US2022119101A1_81184931  total=12  flagged=6
  ✓ US2022126981A1_81076817  total=10  flagged=10
  ✓ US2022126996A1_81257910  total=12  flagged=12
  ✓ US2022126998A1_81076761  total=9  flagged=9
  ✓ US2022135204A1_72521290  total=12  flagged=12
  ✓ US2022144410A1_81255937  total=11  flagged=11
  ✓ US2022144421A1_73652907  total=12  flagged=7
  ✓ US2022144422A1_81381998  total=12  flagged=12
  ✓ US2022144443A1_81256277  total=10  flagged=10
  ✓ US2022161927A1_72518885  total=12  flagged=12
  ✓ US2022169366A1_81752152  total=6  flagged=6
  ✓ US2022169371A1_69941378  total=4  flagged=1
  ✓ US2022169373A1_81585068  total=7  flagged=7
  ✓ US2022169379A1_81752154  total=10  flagged=9
  ✓ US2022169380A1_81752171  total=12  flagged=12
  ✓ US2022177105A1_67190624  total=3  flagged=3
  ✓ US2022177109A1_78725358  total=12  flagged=12
  ✓ US2022177121A1_81849952  total=6  flagged=5
  ✓ US2022185468A1_78827316  total=6  flagged=6
  ✓ US2022185469A1_78821919  total=12  flagged=12
  ✓ US2022194554A1_81847373  total=4  flagged=4
  ✓ US2022194556A1_72608819  total=12  flagged=12
  ✓ US2022194557A1_81608085  total=12  flagged=12
  ✓ US2022194568A1_67999777  total=12  flagged=12
  ✓ US2022194575A1_78957348  total=12  flagged=12
  ✓ US2022194611A1_81847577  total=7  flagged=7
  ✓ US2022194618A1_77465774  total=9  flagged=9
  ✓ US2022197308A1_82023032  total=12  flagged=12
  ✓ US2022204152A1_82119528  total=12  flagged=12
  ✓ US2022212784A1_67734413  total=8  flagged=8
  ✓ US2022219826A1_78617276  total=6  flagged=6
  ✓ US2022234745A1_80121659  total=12  flagged=9
  ✓ US2022242557A1_78617275  total=11  flagged=11
  ✓ US2022243726A1_82612385  total=7  flagged=7
  ✓ US2022250742A1_80628505  total=11  flagged=11
  ✓ US2022250755A1_79269946  total=10  flagged=10
  ✓ US2022266987A1_74672186  total=4  flagged=4
  ✓ US2022266995A1_67839713  total=4  flagged=4
  ✓ US2022266998A1_74672199  total=6  flagged=6
  ✓ US2022267016A1_75223306  total=12  flagged=12
  ✓ US2022271745A1_74672153  total=9  flagged=9
  ✓ US2022274701A1_74502840  total=11  flagged=11
  ✓ US2022274711A1_68654641  total=5  flagged=5
  ✓ US2022275773A1_74797843  total=5  flagged=4
  ✓ US2022281593A1_74859752  total=7  flagged=6
  ✓ US2022281594A1_74859724  total=6  flagged=4
  ✓ US2022289371A1_83194584  total=12  flagged=12
  ✓ US2022297834A1_74884384  total=10  flagged=10
  ✓ US2022306289A1_83364293  total=10  flagged=10
  ✓ US2022306291A1_83364302  total=8  flagged=8
  ✓ US2022306292A1_83364296  total=12  flagged=12
  ✓ US2022306293A1_83364299  total=8  flagged=8
  ✓ US2022306307A1_83364315  total=10  flagged=10
  ✓ US2022315207A1_83450473  total=12  flagged=12
  ✓ US2022315217A1_71096145  total=10  flagged=9
  ✓ US2022315236A1_83448750  total=8  flagged=8
  ✓ US2022315237A1_83406598  total=11  flagged=11
  ✓ US2022324558A1_83510453  total=8  flagged=8
  ✓ US2022348309A1_83808223  total=8  flagged=8
  ✓ US2022348320A1_74859723  total=8  flagged=5
  ✓ US2022348339A1_75728740  total=10  flagged=10
  ✓ US2022355922A1_74100087  total=6  flagged=6
  ✓ US2022355923A1_77930088  total=10  flagged=9
  ✓ US2022355924A1_83901409  total=12  flagged=12
  ✓ US2022355944A1_69468847  total=8  flagged=8
  ✓ US2022363374A1_75437383  total=5  flagged=5
  ✓ US2022363376A1_83999276  total=6  flagged=6
  ✓ US2022363401A1_83999298  total=9  flagged=9
  ✓ US2022371446A1_76076208  total=11  flagged=10
  ✓ US2022371727A1_76355307  total=12  flagged=12
  ✓ US2022375449A1_80683032  total=12  flagged=12
  ✓ US2022376514A1_76076209  total=11  flagged=10
  ✓ US2022380033A1_76730815  total=8  flagged=8
  ✓ US2022380037A1_84193785  total=5  flagged=5
  ✓ US2022388647A1_84284820  total=9  flagged=8
  ✓ US2022388648A1_84284827  total=12  flagged=10
  ✓ US2022388649A1_82358449  total=8  flagged=8
  ✓ US2022388650A1_84284825  total=12  flagged=12
  ✓ US2022388672A1_84284837  total=9  flagged=9
  ✓ US2022402602A1_84491113  total=12  flagged=11
  ✓ US2022402603A1_84491115  total=10  flagged=9
  ✓ US2022402608A1_76687458  total=9  flagged=9
  ✓ US2022411089A1_84542151  total=11  flagged=10
  ✓ US2023006598A1_77670710  total=12  flagged=12
  ✓ US2023009101A1_84798125  total=12  flagged=12
  ✓ US2023021800A1_77353955  total=12  flagged=12
  ✓ US2023025366A1_69525984  total=12  flagged=12
  ✓ US2023025666A1_69525983  total=12  flagged=11
  ✓ US2023026745A1_76863648  total=7  flagged=7
  ✓ US2023033507A1_76559028  total=10  flagged=10
  ✓ US2023038458A1_85153305  total=7  flagged=7
  ✓ US2023041771A1_85153808  total=6  flagged=2
  ✓ US2023056709A1_78114209  total=12  flagged=12
  ✓ US2023056974A1_85227818  total=12  flagged=9
  ✓ US2023067093A1_85285604  total=9  flagged=9
  ✓ US2023067713A1_85287023  total=11  flagged=10
  ✓ US2023086655A1_85573697  total=12  flagged=12
  ✓ US2023091705A1_82786623  total=11  flagged=11
  ✓ US2023118750A1_85982860  total=11  flagged=11
  ✓ US2023121845A1_74874597  total=10  flagged=10
  ✓ US2023122276A1_85981160  total=12  flagged=12
  ✓ US2023143459A1_86229810  total=7  flagged=7
  ✓ US2023150659A1_86325145  total=10  flagged=10
  ✓ US2023174253A1_75690234  total=12  flagged=12
  ✓ US2023182895A1_86498700  total=11  flagged=11
  ✓ US2023182897A1_75690236  total=12  flagged=12
  ✓ US2023182915A1_86695948  total=12  flagged=12
  ✓ US2023192279A1_86769694  total=7  flagged=7
  ✓ US2023192280A1_86767298  total=12  flagged=12
  ✓ US2023192281A1_75825815  total=7  flagged=7
  ✓ US2023192282A1_77930122  total=8  flagged=8
  ✓ US2023192285A1_86767328  total=12  flagged=12
  ✓ US2023192286A1_86767329  total=12  flagged=12
  ✓ US2023192289A1_86767332  total=12  flagged=12
  ✓ US2023192311A1_86767237  total=12  flagged=12
  ✓ US2023195143A1_78745069  total=12  flagged=12
  ✓ US2023202651A1_86898134  total=8  flagged=8
  ✓ US2023202653A1_86898135  total=10  flagged=10
  ✓ US2023203975A1_86898440  total=12  flagged=12
  ✓ US2023211877A1_79230562  total=4  flagged=2
  ✓ US2023219685A1_87070139  total=12  flagged=12
  ✓ US2023227147A1_87162509  total=10  flagged=10
  ✓ US2023227154A1_87162512  total=12  flagged=12
  ✓ US2023234696A1_72356186  total=12  flagged=12
  ✓ US2023234701A1_72147866  total=11  flagged=11
  ✓ US2023234703A1_87313479  total=12  flagged=11
  ✓ US2023234705A1_87313465  total=12  flagged=12
  ✓ US2023242266A1_69468740  total=4  flagged=4
  ✓ US2023249816A1_81209166  total=12  flagged=12
  ✓ US2023257103A1_87559164  total=11  flagged=11
  ✓ US2023257104A1_75690235  total=12  flagged=12
  ✓ US2023257112A1_87559142  total=6  flagged=2
  ✓ US2023257114A1_85384185  total=12  flagged=11
  ✓ US2023257132A1_82448494  total=12  flagged=12
  ✓ US2023264812A1_87573673  total=9  flagged=9
  ✓ US2023266774A1_87573956  total=8  flagged=8
  ✓ US2023271710A1_87762067  total=12  flagged=12
  ✓ US2023271713A1_80036675  total=11  flagged=8
  ✓ US2023278702A1_74698212  total=6  flagged=6
  ✓ US2023286650A1_72519935  total=5  flagged=5
  ✓ US2023303243A1_88095186  total=7  flagged=6
  ✓ US2023303454A1_80491011  total=5  flagged=5
  ✓ US2023305580A1_88048796  total=6  flagged=6
  ✓ US2023307972A1_88096617  total=6  flagged=6
  ✓ US2023312089A1_87766782  total=12  flagged=12
  ✓ US2023312117A1_85726930  total=12  flagged=12
  ✓ US2023312118A1_85726521  total=8  flagged=8
  ✓ US2023318505A1_88192424  total=5  flagged=5
  ✓ US2023322376A1_88240747  total=12  flagged=12
  ✓ US2023322398A1_80952303  total=3  flagged=3
  ✓ US2023331379A1_80949073  total=6  flagged=6
  ✓ US2023331380A1_88309012  total=12  flagged=11
  ✓ US2023339594A1_88416824  total=12  flagged=12
  ✓ US2023339596A1_88416827  total=12  flagged=12
  ✓ US2023339601A1_86424953  total=12  flagged=12
  ✓ US2023339602A1_88416830  total=12  flagged=12
  ✓ US2023339610A1_80777205  total=10  flagged=8
  ✓ US2023348053A1_88513391  total=10  flagged=10
  ✓ US2023348088A1_72356188  total=12  flagged=12
  ✓ US2023356834A1_75825816  total=7  flagged=7
  ✓ US2023356836A1_81600680  total=12  flagged=11
  ✓ US2023382525A1_75252794  total=8  flagged=5
  ✓ US2023382542A1_82059705  total=7  flagged=7
  ✓ US2023387909A1_88697179  total=12  flagged=12
  ✓ US2023399099A1_74871607  total=7  flagged=7
  ✓ US2023406528A1_87377605  total=8  flagged=8
  ✓ US2023406551A1_89170144  total=12  flagged=12
  ✓ US2023407759A1_89169446  total=12  flagged=12
  ✓ US2024002034A1_89381807  total=12  flagged=12
  ✓ US2024002048A1_89434046  total=12  flagged=12
  ✓ US2024002049A1_81709705  total=12  flagged=12
  ✓ US2024018967A1_89510635  total=12  flagged=12
  ✓ US2024025540A1_74554073  total=12  flagged=11
  ✓ US2024034466A1_82057443  total=9  flagged=9
  ✓ US2024051687A1_75787040  total=12  flagged=12
  ✓ US2024059393A1_82057436  total=7  flagged=6
  ✓ US2024059410A1_89907336  total=12  flagged=12
  ✓ US2024061444A1_89906646  total=8  flagged=8
  ✓ US2024067328A1_87845818  total=9  flagged=9
  ✓ US2024076031A1_87889355  total=7  flagged=7
  ✓ US2024083588A1_90142398  total=12  flagged=12
  ✓ US2024092484A1_90245238  total=9  flagged=9
  ✓ US2024097521A1_90243251  total=8  flagged=8
  ✓ US2024109652A1_90471436  total=9  flagged=9
  ✓ US2024109653A1_88204246  total=5  flagged=5
  ✓ US2024116629A1_90574686  total=12  flagged=12
  ✓ US2024124128A1_76070062  total=5  flagged=3
  ✓ US2024124134A1_90627934  total=12  flagged=12
  ✓ US2024124135A1_90627935  total=10  flagged=10
  ✓ US2024132207A1_91281361  total=4  flagged=4
  ✓ US2024140598A1_90835437  total=10  flagged=8
  ✓ US2024140601A1_84044891  total=5  flagged=5
  ✓ US2024140627A1_90835339  total=12  flagged=12
  ✓ US2024150013A1_88731244  total=11  flagged=11
  ✓ US2024154490A1_88745802  total=6  flagged=6
  ✓ US2024166333A1_88837316  total=11  flagged=11
  ✓ US2024166345A1_91081494  total=12  flagged=12
  ✓ US2024167561A1_75870344  total=9  flagged=9
  ✓ US2024174355A1_91078714  total=12  flagged=12
  ✓ US2024174356A1_89029491  total=8  flagged=8
  ✓ US2024174369A1_90231699  total=6  flagged=6
  ✓ US2024183394A1_83456345  total=12  flagged=12
  ✓ US2024190561A1_84545444  total=12  flagged=12
  ✓ US2024190562A1_87519975  total=12  flagged=12
  ✓ US2024208643A1_83320212  total=11  flagged=11
  ✓ US2024213855A1_85988594  total=12  flagged=12
  ✓ US2024217652A1_91666981  total=9  flagged=9
  ✓ US2024217653A1_91666994  total=10  flagged=9
  ✓ US2024246668A1_84919591  total=7  flagged=7
  ✓ US2024246669A1_77126975  total=12  flagged=4
  ✓ US2024250527A1_91953143  total=6  flagged=6
  ✓ US2024253778A1_91964961  total=9  flagged=7
  ✓ US2024253779A1_91964947  total=6  flagged=5
  ✓ US2024270378A1_77274646  total=12  flagged=8
  ✓ US2024270382A1_85225077  total=6  flagged=3
  ✓ US2024272652A1_87278875  total=12  flagged=12
  ✓ US2024278904A1_92304806  total=12  flagged=12
  ✓ US2024278923A1_92304819  total=5  flagged=5
  ✓ US2024286736A1_76838812  total=4  flagged=3
  ✓ US2024294246A1_92545312  total=9  flagged=9
  ✓ US2024300642A1_92635981  total=11  flagged=11
  ✓ US2024300643A1_92600596  total=12  flagged=12
  ✓ US2024300644A1_80629782  total=12  flagged=12
  ✓ US2024300663A1_92635940  total=11  flagged=11
  ✓ US2024308652A1_88833850  total=5  flagged=5
  ✓ US2024313666A1_92713630  total=12  flagged=12
  ✓ US2024317395A1_92803854  total=12  flagged=12
  ✓ US2024317416A1_87348104  total=12  flagged=12
  ✓ US2024326983A1_92898238  total=12  flagged=12
  ✓ US2024327006A1_92898244  total=8  flagged=8
  ✓ US2024327016A1_92859002  total=7  flagged=7
  ✓ US2024327020A1_92850057  total=8  flagged=8
  ✓ US2024343425A1_78150233  total=6  flagged=6
  ✓ US2024359791A1_82270692  total=9  flagged=9
  ✓ US2024367808A1_87348202  total=12  flagged=12
  ✓ US2024375799A1_93380199  total=10  flagged=9
  ✓ US2024383602A1_93464719  total=12  flagged=12
  ✓ US2024391597A1_93566089  total=8  flagged=8
  ✓ US2024400199A1_93653451  total=9  flagged=9
  ✓ US2024409209A1_91853640  total=12  flagged=12
  ✓ US2024409210A1_84029103  total=10  flagged=10
  ✓ US2024417073A1_93844881  total=9  flagged=9
  ✓ US2024418093A1_93844949  total=12  flagged=11
  ✓ US2025002145A1_93940122  total=12  flagged=12
  ✓ US2025002146A1_84922589  total=7  flagged=7
  ✓ US2025010996A1_86157955  total=12  flagged=12
  ✓ US2025015734A1_87074692  total=6  flagged=6
  ✓ US2025019072A1_94211740  total=12  flagged=10
  ✓ US2025019086A1_94211756  total=12  flagged=12
  ✓ US2025026472A1_94260607  total=8  flagged=8
  ✓ US2025033757A1_94373170  total=10  flagged=10
  ✓ US2025034930A1_94372833  total=7  flagged=7
  ✓ US2025042542A1_81386524  total=7  flagged=7
  ✓ US2025042543A1_87577924  total=12  flagged=10
  ✓ US2025058870A1_85157348  total=6  flagged=6
  ✓ US2025066015A1_94690144  total=12  flagged=12
  ✓ US2025066017A1_89382643  total=12  flagged=12
  ✓ US2025066028A1_94690098  total=12  flagged=12
  ✓ US2025074586A1_84205281  total=5  flagged=4
  ✓ US2025083808A1_94873407  total=12  flagged=11
  ✓ US2025083809A1_87279534  total=12  flagged=10
  ✓ US2025091713A1_94977106  total=8  flagged=8
  ✓ US2025115363A1_82196352  total=6  flagged=6
  ✓ US2025121937A1_76059751  total=12  flagged=12
  ✓ US2025136287A1_80735527  total=7  flagged=7
  ✓ US2025145283A1_95562765  total=12  flagged=12
  ✓ US2025162736A1_87472550  total=12  flagged=12
  ✓ US2025171141A1_95822942  total=12  flagged=12
  ✓ US2025172947A1_94161717  total=12  flagged=12
  ✓ US2025187742A1_95941667  total=12  flagged=12
  ✓ US2025238031A1_90669146  total=12  flagged=12
  ✓ US2025242909A1_96501972  total=4  flagged=4
  ✓ US2025256840A1_94283703  total=10  flagged=10
  ✓ US2025256841A1_94633298  total=8  flagged=8
  ✓ US2025269972A1_90572496  total=8  flagged=8
  ✓ US2025282477A1_88647015  total=11  flagged=7
  ✓ US2025304243A1_97177832  total=7  flagged=7
  ✓ US2025304249A1_82403562  total=10  flagged=8
  ✓ US2025313336A1_82446423  total=10  flagged=8
  ✓ US2025320005A1_91717003  total=12  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US9764833B1_59828939  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US9783288B1_59982119  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US9809300B1_60189454  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US9898033B1_61188379  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US9957042B1_62016727  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US9975631B1_62122158  total=12  flagged=12
  ✓ USD1017462S_90124466  total=10  flagged=10
  ✓ USD1082648S_91031294  total=11  flagged=11
  ✓ USD707614S_50944455  total=4  flagged=4
  ✓ USD731394S_53268292  total=11  flagged=11
  ✓ USD739335S_54107398  total=11  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ USD772137S_57287601  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ USD808328S_60331359  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ USD892710S_71898358  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ USD902828S_73446241  total=8  flagged=8
  ✓ USD912602S_74783249  total=5  flagged=5
  ✓ USD921565S_76160396  total=8  flagged=8
  ✓ WO2010024593A2_41722115  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2010132901A1_43085383  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2012047337A1_48749592  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2012113576A1_45808734  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2012117197A2_45928951  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2013062312A1_48168070  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2015089679A1_52010991  total=8  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2015094020A2_53403854  total=3  flagged=2

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2015143098A2_54145474  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2015189684A1_51905225  total=9  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2016004852A1_55063579  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2016028358A2_55351369  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2016062223A1_55760294  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2017021391A1_56567595  total=9  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2017035503A1_58101065  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2017042291A1_54065807  total=12  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2018038822A1_61245235  total=9  flagged=9

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2018187844A1_63792087  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2018200879A1_63920171  total=12  flagged=10
  ✓ WO2018232340A1_64660749  total=5  flagged=5
  ✓ WO2019005467A2_64742574  total=2  flagged=2
  ✓ WO2019010554A1_65000931  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2019062257A1_65900492  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2019091549A1_60388019  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2019202493A1_66794036  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2019211875A1_68386248  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2019212744A1_68386265  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2020003657A1_68986955  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2020183739A1_72426677  total=11  flagged=11

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2020190223A1_72521011  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2020256571A1_74040593  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2020260581A1_71515123  total=3  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2021029947A2_74569388  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2021070363A1_75438133  total=8  flagged=8

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2021112940A1_76221125  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2021155385A1_74759504  total=7  flagged=7
  ✓ WO2022180755A1_83048976  total=12  flagged=11
  ✓ WO2022180968A1_83047939  total=12  flagged=8
  ✓ WO2022225421A1_83722464  total=3  flagged=3
  ✓ WO2023021054A1_83318998  total=6  flagged=6
  ✓ WO2023051929A1_78080289  total=4  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2023211639A1_88519502  total=12  flagged=12
  ✓ WO2023272353A1_84689755  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2024013392A1_87418680  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ WO2024020362A1_89618566  total=10  flagged=10
  ✓ WO2024076966A1_88689476  total=12  flagged=12
  ✓ WO2024151705A1_89977947  total=7  flagged=6
  ✓ WO2024153885A1_86007350  total=6  flagged=6
  ✓ WO2024153886A1_86007085  total=6  flagged=6
  ✓ WO2024154415A1_91955601  total=1  flagged=1
  ✓ WO2024164048A1_92261759  total=8  flagged=7
  ✓ WO2024168389A1_92421352  total=10  flagged=10
  ✓ WO2024178469A1_92589006  total=8  flagged=8
  ✓ WO2024182866A1_92673862  total=6  flagged=6
  ✓ WO2024191152A1_92755439  total=6  flagged=6
  ✓ WO2024227493A1_93334018  total=3  flagged=3
  ✓ WO2024233261A2_93430973  total=7  flagged=7
  ✓ WO2024233650A1_91585552  total=12  flagged=12
  ✓ WO2024246895A1_93656806  total=12  flagged=12
  ✓ WO2024252755A1_93795837  total=12  flagged=12
  ✓ WO2025014192A1_94215603  total=12  flagged=12
  ✓ WO2025065072A1_95203924  total=12  flagged=9
  ✓ WO2025106962A1_95743549  total=4  flagged=4
  ✓ WO2025109312A1_93741523  total=8  flagged=7
  ✓ WO2025116483A1_95896929  total=12  flagged=11
  ✓ WO2025116490A1_95896983  total=12  flagged=11
  ✓ WO2025177317A2_96847902  total=10  flagged=10
  ✓ WO2025191799A1_97063185  total=4  flagged=4
  ✓ WO2025193300A2_96700852  total=11  flagged=11
  ✓ WO2025216782A2_97102084  total=11  flagged=11
  ✓ WO2025220308A1_97403521  total=4  flagged=4
  ✓ WO2025222250A1_97489048  total=6  flagged=6
  ✓ WO2025236002A1_97675768  total=6  flagged=6
  ✓ WO2025255583A1_97961258  total=12  flagged=12
  ✓ WO2026017242A1_92295556  total=11  flagged=8
  ✓ WO2026024461A1_96774105  total=6  flagged=6
  ✓ WO2026039025A2_98781516  total=5  flagged=5
  ✓ WO2026043536A1_96391479  total=12  flagged=11
  ✓ WO2026050585A1_98932098  total=12  flagged=12
  ✓ WO2026059618A2_98732607  total=12  flagged=11
  ✓ WO2026062567A1_97405922  total=4  flagged=0
  ✓ WO2026070350A1_99307108  total=12  flagged=12
  ✓ WO2026080998A1_99513055  total=12  flagged=12

Triage complete: 1614 patents newly scored | 13835 images | 13284 flagged (96.0% of newly-scored)
Summary written to: /mnt/storage_11tb/Drive_files_to_syncronize/3 - Images DataSets & Labelling Outputs/1639_DS/triage/triage_summary.csv

## Cell 3b — Re-threshold existing results (no GPU needed)

Already-confirmed discards (`keep=False`) are **never** upgraded back.  
Only images currently `keep=True` are re-evaluated against the new threshold.  
Rewrites all JSONs and `triage_summary.csv` in-place.

In [4]:
import importlib, triage_filter
importlib.reload(triage_filter)   # pick up src edits without restarting kernel

# ── Choose mode ───────────────────────────────────────────────────────────────
#
#   "add"   — rethreshold_existing: only ADDS new discards, never re-enables
#             anything already marked keep=False (safe, one-way)
#
#   "reset" — reset_threshold: re-derives keep from raw scores for ALL images,
#             works in both directions — use this to undo an over-aggressive run
#
MODE      = "reset"   # "add" | "reset"
THRESHOLD = 0.51      # tune this valuel
# ─────────────────────────────────────────────────────────────────────────────

if MODE == "add":
    triage_filter.rethreshold_existing(cfg, new_threshold=THRESHOLD)
elif MODE == "reset":
    triage_filter.reset_threshold(cfg, threshold=THRESHOLD)
else:
    print(f"Unknown MODE={MODE!r} — choose 'add' or 'reset'")

Reset complete (threshold=0.51): 13835 images | 3418 flagged (24.7%)
Summary rewritten: /mnt/storage_11tb/Drive_files_to_syncronize/3 - Images DataSets & Labelling Outputs/1639_DS/triage/triage_summary.csv

## Cell 5b — Lock/unlock (advanced)

Use **only** if you need direct control over locks outside the normal review flow.

| Action | Effect |
|--------|--------|
| `lock_discards` | Lock all current DISCARDs — they won't reappear in the viewer |
| `lock_keeps` | Lock all current KEEPs — aggressive threshold won't remove them |
| `unlock_all` | Clear every lock (full clean slate) |
| `stats` | Show current lock counts (no writes) |

> **Normal workflow:** use the Cell 6 viewer + the Commit cell at the bottom instead.

In [5]:
import importlib, triage_filter
importlib.reload(triage_filter)

# ── Choose lock action ────────────────────────────────────────────────────────
#
#   "lock_discards"  — protect current DISCARDs; threshold raises cannot re-enable them
#   "lock_keeps"     — protect current KEEPs; threshold raises cannot discard them
#   "unlock_all"     — clear all locks (clean slate before a full reset)
#   "stats"          — just print the current lock counts (no writes)
#   None             — do nothing
#
LOCK_ACTION = "stats"   # change to "lock_discards", "lock_keeps", or "unlock_all"
# ─────────────────────────────────────────────────────────────────────────────

if LOCK_ACTION == "lock_discards":
    triage_filter.lock_discards(cfg)
elif LOCK_ACTION == "lock_keeps":
    triage_filter.lock_keeps(cfg)
elif LOCK_ACTION == "unlock_all":
    triage_filter.unlock_all(cfg)
elif LOCK_ACTION == "stats":
    triage_filter.locked_stats(cfg)
else:
    print("LOCK_ACTION not set — nothing done.")

Triage lock status (13835 images total):
  Locked DISCARD : 0
  Locked KEEP    : 0
  Free (unlocked): 13,835

In [6]:
import json
import pandas as pd

triage_path = Path(cfg["paths"]["triage"])
summary_csv = triage_path / "triage_summary.csv"

if not summary_csv.exists():
    print("No triage_summary.csv found — run Cell 3 first.")
else:
    summary_df = pd.read_csv(summary_csv)

    total_images  = summary_df["total_images"].sum()
    total_flagged = summary_df["flagged_count"].sum()
    overall_ratio = total_flagged / max(1, total_images)

    print(f"Total images scored : {total_images}")
    print(f"Total flagged       : {total_flagged}")
    print(f"Overall flagged ratio: {overall_ratio:.1%}")
    print()

    # Show per-figure results for the 3 patents with the most flagged images
    top3 = summary_df.nlargest(3, "flagged_count")[["patent_id", "total_images", "flagged_count", "flagged_ratio"]]
    print("Top 3 patents by flagged count:")
    display(top3.reset_index(drop=True))
    print()

    for patent_id in top3["patent_id"]:
        json_path = triage_path / f"{patent_id}.json"
        if not json_path.exists():
            print(f"  {patent_id}: JSON not found")
            continue
        with open(json_path) as fh:
            data = json.load(fh)
        figures_df = pd.DataFrame(data["figures"])
        print(f"\n--- {patent_id}  (total={data['total']}  flagged={data['flagged']}) ---")
        display(figures_df[["file", "pred", "score_drawing", "score_table", "keep"]])

Total images scored : 13835
Total flagged       : 3418
Overall flagged ratio: 24.7%

Top 3 patents by flagged count:

               patent_id  total_images  flagged_count  flagged_ratio
0  CN116280179A_86786318            12             12            1.0
1  CN119099860A_93717638            12             12            1.0
2  CN120191516A_96063272            12             12            1.0

--- CN116280179A_86786318  (total=12  flagged=12) ---

,file,pred,score_drawing,score_table,keep
0,CN116280179APAFP.png,table,0.4875,0.5127,False
1,CN116280179A_202310171305.png,table,0.4875,0.5127,False
2,CN116280179A_HDA0004099463590000012.png,table,0.4956,0.5044,False
3,CN116280179A_HDA0004099463590000021.png,table,0.4949,0.5054,False
4,CN116280179A_HDA0004099463590000022.png,table,0.4944,0.5054,False
5,CN116280179A_HDA0004099463590000031.png,table,0.4910,0.5093,False
6,CN116280179A_HDA0004099463590000032.png,table,0.4834,0.5166,False
7,CN116280179A_HDA0004099463590000041.png,table,0.5054,0.4949,False
8,CN116280179A_HDA0004099463590000042.png,table,0.4878,0.5122,False
9,CN116280179A_HDA0004099463590000051.png,table,0.4890,0.5107,False
10,CN116280179A_HDA0004099463590000052.png,table,0.4973,0.5024,False
11,CN116280179A_HDA0004099463590000061.png,table,0.4951,0.5049,False

--- CN119099860A_93717638  (total=12  flagged=12) ---

                    file   pred  score_drawing  score_table   keep
0       202411421431.png  table         0.5020       0.4980  False
1   CN119099860APAFP.png  table         0.5020       0.4980  False
2               FT_1.png  table         0.4910       0.5093  False
3              FT_10.png  table         0.4924       0.5078  False
4               FT_2.png  table         0.4880       0.5122  False
5               FT_3.png  table         0.5020       0.4980  False
6               FT_4.png  table         0.4871       0.5127  False
7               FT_5.png  table         0.4951       0.5049  False
8               FT_6.png  table         0.4858       0.5142  False
9               FT_7.png  table         0.4961       0.5039  False
10              FT_8.png  table         0.4917       0.5083  False
11              FT_9.png  table         0.4910       0.5088  False

--- CN120191516A_96063272  (total=12  flagged=12) ---

,file,pred,score_drawing,score_table,keep
0,CN120191516APAFP.png,table,0.4893,0.5107,False
1,CN120191516A_202411687048.png,table,0.4893,0.5107,False
2,CN120191516A_HDA0005149869780000021.png,table,0.4883,0.5117,False
3,CN120191516A_HDA0005149869780000031.png,table,0.4958,0.5044,False
4,CN120191516A_HDA0005149869780000041.png,table,0.4980,0.5020,False
5,CN120191516A_HDA0005149869780000051.png,table,0.4814,0.5186,False
6,CN120191516A_HDA0005149869780000052.png,table,0.4836,0.5166,False
7,CN120191516A_HDA0005149869780000053.png,table,0.4873,0.5127,False
8,CN120191516A_HDA0005149869780000061.png,table,0.4900,0.5098,False
9,CN120191516A_HDA0005149869780000062.png,table,0.4895,0.5103,False
10,CN120191516A_HDA0005149869780000071.png,table,0.4800,0.5200,False
11,CN120191516A_HDA0005149869780000081.png,table,0.4714,0.5288,False

## Cell 5 — Visual inspection: kept vs. discarded images

Shows the actual images for one patent so you can judge whether the threshold is working correctly.  
- **Green border** = kept (`keep=True`, `score_drawing ≥ threshold`)  
- **Red border** = discarded (`keep=False`)  

Change `INSPECT_PATENT` to any patent ID from the triage results, or leave it as `None` to auto-pick the first processed patent.

In [7]:
import json
import math
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import ipywidgets as widgets
from IPython.display import display, clear_output
from pathlib import Path
from PIL import Image

triage_path = Path(cfg["paths"]["triage"])
raw_dir     = Path(cfg["paths"]["raw_images"])
MAX_COLS    = 4

# All processed patents, sorted
patent_ids = sorted(p.stem for p in triage_path.glob("*.json")
                    if p.stem != "triage_summary")
if not patent_ids:
    print("No triage JSON files found — run Cell 3 first.")
    raise SystemExit

print(f"Found {len(patent_ids)} processed patents. Use the buttons or dropdown to navigate.")

# ── Widgets ───────────────────────────────────────────────────────────────────
idx_state   = {"i": 0, "updating": False}   # flag prevents dropdown re-entrancy
out         = widgets.Output()
btn_prev    = widgets.Button(description="◀ Prev", button_style="info",  layout=widgets.Layout(width="120px"))
btn_next    = widgets.Button(description="Next ▶", button_style="info",  layout=widgets.Layout(width="120px"))
lbl_pos     = widgets.Label(value=f"1 / {len(patent_ids)}")
patent_dd   = widgets.Dropdown(options=patent_ids, value=patent_ids[0],
                                layout=widgets.Layout(width="360px"))

def show_patent(patent_id):
    json_path = triage_path / f"{patent_id}.json"
    with open(json_path) as fh:
        data = json.load(fh)
    figures = data["figures"]
    n       = len(figures)
    if n == 0:
        print(f"{patent_id}: no figures in triage JSON")
        return
    n_kept  = sum(1 for f in figures if f["keep"])
    n_disc  = n - n_kept

    n_cols = min(MAX_COLS, n)
    n_rows = math.ceil(n / n_cols)
    fig, axes = plt.subplots(n_rows, n_cols,
                             figsize=(n_cols * 1.8, n_rows * 2.0),
                             squeeze=False, dpi=80)
    flat_axes = [ax for row in axes for ax in row]

    patent_dir = raw_dir / patent_id
    for ax, fig_info in zip(flat_axes, figures):
        img_path = patent_dir / fig_info["file"]
        try:
            img = Image.open(img_path).convert("RGB")
            ax.imshow(img)
        except Exception:
            ax.text(0.5, 0.5, "not found", ha="center", va="center",
                    color="grey", transform=ax.transAxes)
        keep  = fig_info["keep"]
        color = "#2ecc71" if keep else "#e74c3c"
        label = "KEEP" if keep else "DISCARD"
        for spine in ax.spines.values():
            spine.set_edgecolor(color)
            spine.set_linewidth(4)
        ax.set_title(f"{fig_info['file']}\n{label}  {fig_info['score_drawing']:.3f}",
                     fontsize=7, color=color, pad=3)
        ax.set_xticks([]); ax.set_yticks([])

    for ax in flat_axes[n:]:
        ax.axis("off")

    keep_patch    = mpatches.Patch(color="#2ecc71", label=f"Kept ({n_kept})")
    discard_patch = mpatches.Patch(color="#e74c3c", label=f"Discarded ({n_disc})")
    fig.legend(handles=[keep_patch, discard_patch], loc="lower center",
               ncol=2, fontsize=10, frameon=False, bbox_to_anchor=(0.5, -0.01))
    fig.suptitle(f"{patent_id}  —  {n_kept}/{n} kept  (threshold={THRESHOLD})",
                 fontsize=12, fontweight="bold", y=1.01)
    plt.tight_layout()
    plt.show()

def refresh():
    i = idx_state["i"]
    # Update label and dropdown without triggering the observer callback
    lbl_pos.value = f"{i+1} / {len(patent_ids)}"
    idx_state["updating"] = True
    patent_dd.value = patent_ids[i]
    idx_state["updating"] = False
    with out:
        clear_output(wait=True)
        show_patent(patent_ids[i])

def on_prev(_):
    if idx_state["i"] > 0:
        idx_state["i"] -= 1
        refresh()

def on_next(_):
    if idx_state["i"] < len(patent_ids) - 1:
        idx_state["i"] += 1
        refresh()

def on_dropdown(change):
    # Only react to user-driven value changes, not programmatic ones from refresh()
    if change["name"] == "value" and not idx_state["updating"]:
        new_val = change["new"]
        if new_val in patent_ids:
            idx_state["i"] = patent_ids.index(new_val)
            refresh()

btn_prev.on_click(on_prev)
btn_next.on_click(on_next)
patent_dd.observe(on_dropdown)

nav_bar = widgets.HBox([btn_prev, lbl_pos, btn_next, patent_dd])
display(nav_bar, out)
refresh()

Found 1614 processed patents. Use the buttons or dropdown to navigate.

HBox(children=(Button(button_style='info', description='◀ Prev', layout=Layout(width='120px'), style=ButtonSty…

Output()

## Cell 6 — Review pending discards

Shows every image flagged as **discarded** that has **not yet been locked** (i.e. not reviewed in a previous session).

- **Red border** = DISCARD — will be permanently locked on Commit
- **Green border** = APPROVED — will be flipped to KEEP on Commit

Click any image to toggle between DISCARD and APPROVED.  Nothing is written to disk until you run the **Commit cell** below.

> Already-locked images (from previous sessions) are hidden — run `reset_review` in the Commit cell to bring them back.

In [3]:
import importlib, triage_filter
importlib.reload(triage_filter)

import json, math, threading
import matplotlib
matplotlib.use("widget")
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, clear_output
from pathlib import Path
from PIL import Image

triage_path = Path(cfg["paths"]["triage"])
raw_dir     = Path(cfg["paths"]["raw_images"])

PAGE_SIZE = 200
MAX_COLS  = 5

# ── Load non-locked discarded images only ─────────────────────────────────────
# Images already locked (reviewed in a previous session) are hidden.
def load_pending_discards():
    result = []
    for json_path in sorted(triage_path.glob("*.json")):
        if json_path.stem == "triage_summary":
            continue
        with open(json_path) as fh:
            data = json.load(fh)
        for fig in data["figures"]:
            if not fig["keep"] and not fig.get("locked"):
                result.append({
                    "patent_id":     json_path.stem,
                    "file":          fig["file"],
                    "score_drawing": fig["score_drawing"],
                    "score_table":   fig["score_table"],
                })
    return result

discarded = load_pending_discards()

# approved: images the user clicked to flip to KEEP this session (not yet on disk)
approved  = set()

# visited_pages: page indices actually rendered (shown) this session. Commit
# only locks images belonging to these pages — pages you never scroll to stay
# pending instead of being silently locked as DISCARD by default.
visited_pages = set()

n_total = len(discarded)
n_pages = max(1, math.ceil(n_total / PAGE_SIZE))
print(f"Pending review (non-locked discards): {n_total}  ({n_pages} pages of {PAGE_SIZE})")
print("  Red border  = DISCARD  (will be locked on Commit)")
print("  Green border = APPROVED (will be set to KEEP on Commit)")
print("  Click any image to toggle it to APPROVED.")
print("  Only pages you actually view here get committed — unvisited pages stay pending.")
print()
print("When done reviewing, run the LAST CELL to commit your decisions to disk.")

# ── Widgets ───────────────────────────────────────────────────────────────────
page_state = {"p": 0, "fig": None, "flat_axes": [], "batch": []}
out_disc   = widgets.Output()
btn_dp     = widgets.Button(description="◀ Prev", button_style="warning", layout=widgets.Layout(width="120px"))
btn_dn     = widgets.Button(description="Next ▶", button_style="warning", layout=widgets.Layout(width="120px"))
lbl_dp     = widgets.Label(value=f"Page 1 / {n_pages}")
lbl_info   = widgets.Label(value="")
lbl_counts = widgets.Label(value=f"Approved: 0 / {n_total}")
btn_commit = widgets.Button(description="Commit Page & Next", button_style="success", layout=widgets.Layout(width="180px"))
committed_pages = set()

def _ax_color(entry):
    key = (entry["patent_id"], entry["file"])
    return ("#2ecc71", "APPROVED ✓") if key in approved else ("#e74c3c", "DISCARD")

def show_page(p):
    batch  = discarded[p * PAGE_SIZE : (p + 1) * PAGE_SIZE]
    n      = len(batch)
    if n == 0:
        return
    visited_pages.add(p)
    n_cols = min(MAX_COLS, n)
    n_rows = math.ceil(n / max(n_cols, 1))

    if page_state["fig"] is not None:
        plt.close(page_state["fig"])

    fig, axes = plt.subplots(n_rows, n_cols,
                             figsize=(n_cols * 3.2, n_rows * 3.4),
                             squeeze=False, dpi=80)
    flat_axes = [ax for row in axes for ax in row]
    page_state.update({"fig": fig, "flat_axes": flat_axes, "batch": batch})

    for ax, entry in zip(flat_axes, batch):
        img_path = raw_dir / entry["patent_id"] / entry["file"]
        try:
            img = Image.open(img_path).convert("RGB")
            ax.imshow(img)
        except Exception:
            ax.text(0.5, 0.5, "not found", ha="center", va="center",
                    color="grey", transform=ax.transAxes)
        ax.set_xticks([]); ax.set_yticks([])
        color, label = _ax_color(entry)
        for spine in ax.spines.values():
            spine.set_edgecolor(color)
            spine.set_linewidth(4)
        ax.set_title(
            f"{entry['patent_id']}\n{entry['file']}\n{label}  draw={entry['score_drawing']:.3f}",
            fontsize=6, color=color, pad=3
        )

    for ax in flat_axes[n:]:
        ax.axis("off")

    fig.suptitle(
        f"Pending discards — page {p+1}/{n_pages}  "
        f"(images {p*PAGE_SIZE+1}–{p*PAGE_SIZE+n} of {n_total})  "
        f"| Click image → APPROVED",
        fontsize=10, fontweight="bold"
    )
    plt.tight_layout()

    def on_click(event):
        if event.inaxes is None:
            return
        fa, ba = page_state["flat_axes"], page_state["batch"]
        for i, ax in enumerate(fa[:len(ba)]):
            if ax is event.inaxes:
                entry = ba[i]
                key   = (entry["patent_id"], entry["file"])
                # toggle
                if key in approved:
                    approved.discard(key)
                else:
                    approved.add(key)
                color, label = _ax_color(entry)
                for spine in ax.spines.values():
                    spine.set_edgecolor(color)
                    spine.set_linewidth(4)
                ax.set_title(
                    f"{entry['patent_id']}\n{entry['file']}\n{label}  draw={entry['score_drawing']:.3f}",
                    fontsize=6, color=color, pad=3
                )
                fig.canvas.draw_idle()
                lbl_info.value   = f"{'✓ APPROVED' if key in approved else '✗ back to DISCARD'}: {entry['patent_id']} / {entry['file']}"
                lbl_counts.value = f"Approved: {len(approved)} / {n_total}"
                return

    fig.canvas.mpl_connect("button_press_event", on_click)
    plt.show()

def refresh_disc(new_p):
    page_state["p"] = new_p
    lbl_dp.value    = f"Page {new_p + 1} / {n_pages}"
    lbl_info.value  = ""
    with out_disc:
        clear_output(wait=True)
        show_page(new_p)

def commit_current_page(_):
    p = page_state["p"]
    batch = page_state["batch"]
    if not batch:
        return
    stats = triage_filter.commit_batch(cfg, batch, approved)
    committed_pages.add(p)
    lbl_info.value = (
        f"✓ Page {p+1} committed to disk — "
        f"{stats['newly_kept']} kept, {stats['newly_locked_discard']} discarded."
    )
    if p < n_pages - 1:
        refresh_disc(p + 1)
    else:
        with out_disc:
            clear_output(wait=True)
            print("Last page — all reviewed pages committed.")

btn_commit.on_click(commit_current_page)
btn_dp.on_click(lambda _: refresh_disc(page_state["p"] - 1) if page_state["p"] > 0 else None)
btn_dn.on_click(lambda _: refresh_disc(page_state["p"] + 1) if page_state["p"] < n_pages - 1 else None)

display(widgets.HBox([btn_dp, lbl_dp, btn_dn, btn_commit, lbl_counts, lbl_info]), out_disc)
refresh_disc(0)

Pending review (non-locked discards): 18  (1 pages of 200)
  Red border  = DISCARD  (will be locked on Commit)
  Green border = APPROVED (will be set to KEEP on Commit)
  Click any image to toggle it to APPROVED.
  Only pages you actually view here get committed — unvisited pages stay pending.

When done reviewing, run the LAST CELL to commit your decisions to disk.

HBox(children=(Button(button_style='warning', description='◀ Prev', layout=Layout(width='120px'), style=Button…

Output()

## Cell 7 — Commit review decisions

Writes your Cell-6 review session to disk.

| `COMMIT_ACTION` | Effect |
|-----------------|--------|
| `"commit"` | Lock every APPROVED image as KEEP, lock every remaining DISCARD as discarded. They won't appear in the viewer again. |
| `"reset_review"` | Remove all discard locks — images reappear in Cell 6 for another review pass. Locked KEEPs are preserved. |
| `"stats"` | Show current lock counts (no writes). |

> **Typical session:**  
> 1. Run Cell 6, flip the false-positives to APPROVED  
> 2. Run this cell with `COMMIT_ACTION = "commit"`  
> 3. Next time you open the notebook, only *new* unreviewed discards show up  

> **To start fresh** (e.g. after changing threshold):  
> Set `COMMIT_ACTION = "reset_review"`, then re-run Cell 3b with `MODE = "reset"`

In [9]:
import importlib, triage_filter
importlib.reload(triage_filter)

# ── Choose action ─────────────────────────────────────────────────────────────
#
#   "commit"        — write this session's decisions to disk (only pages you
#                     actually viewed in Cell 6 above — see reviewed_keys below)
#   "reset_review"  — unlock discard locks so they reappear in the viewer
#   "stats"         — show lock counts only (no writes)
#
COMMIT_ACTION = "commit"
# ─────────────────────────────────────────────────────────────────────────────

if COMMIT_ACTION == "commit":
    # `approved` and `visited_pages` are built up in Cell 6 above.
    # Only images on pages you actually viewed get committed — anything you
    # never scrolled to stays pending instead of being silently locked as
    # discard. If Cell 6 wasn't run this session, both default to empty so
    # this commit is a safe no-op rather than mass-locking everything pending.
    try:
        _approved = approved
        _visited_pages = visited_pages
    except NameError:
        _approved = set()
        _visited_pages = set()
        print("⚠  Cell 6 was not run this session — nothing to commit.")

    _reviewed_keys = {
        (fig["patent_id"], fig["file"])
        for p in _visited_pages
        for fig in discarded[p * PAGE_SIZE : (p + 1) * PAGE_SIZE]
    }
    triage_filter.commit_review(cfg, _approved, reviewed_keys=_reviewed_keys)

elif COMMIT_ACTION == "reset_review":
    triage_filter.reset_review(cfg)

elif COMMIT_ACTION == "stats":
    triage_filter.locked_stats(cfg)

else:
    print(f"Unknown COMMIT_ACTION={COMMIT_ACTION!r} — choose commit / reset_review / stats")

commit_review: 0 images flipped to KEEP (locked).
               3418 discards locked permanently.
Summary rewritten: /mnt/storage_11tb/Drive_files_to_syncronize/3 - Images DataSets & Labelling Outputs/1639_DS/triage/triage_summary.csv