In [8]:
import sys
import os
from pathlib import Path

notebook_dir = Path(os.getcwd())
project_root = notebook_dir.parent
src_dir      = project_root / "src"

if str(src_dir) not in sys.path:
    sys.path.insert(0, str(src_dir))

from config_loader import load_config
import triage_filter

cfg = load_config()

# Resolve triage path (new key — created by run_triage if absent)
triage_path = Path(cfg["paths"]["triage"])

print("Config loaded.")
print("  raw_images :", cfg["paths"]["raw_images"])
print("  triage     :", triage_path)

Config loaded.
  raw_images : /mnt/storage_11tb/Drive_files_to_syncronize/3 - Images DataSets & Labelling Outputs/1639_DS/raw
  triage     : /mnt/storage_11tb/Drive_files_to_syncronize/3 - Images DataSets & Labelling Outputs/1639_DS/triage

# Stage 00a.2 — SigLIP Triage Filter

**What this notebook does:**  
Scores every raw patent image with [SigLIP](https://huggingface.co/timm/ViT-SO400M-14-SigLIP-384) (a large vision-language model) to detect images that are **not technical drawings** — tables, text pages, data grids, title sheets — before those images enter the expensive labelling pipeline downstream.

It is **completely non-destructive**: nothing in `raw/` is touched. Outputs are JSON/CSV manifests only.

---

## Why this step exists

PatSeer downloads *everything* on the Drawings tab — which often includes:
- Cover pages / title sheets
- Tables of component labels
- Text-only description pages
- Flowcharts and block diagrams that look like drawings but aren't figure crops

Running `00b` (figure crop + label matching) on those wastes GPU time and pollutes the labelled dataset. This step flags them so Stage `00b` can skip them.

---

## How the scoring works

Each image is scored against two zero-shot text prompts using SigLIP:

| Prompt | Meaning |
|--------|---------|
| `"a technical patent line drawing of an aircraft or mechanical component"` | → `score_drawing` |
| `"a table, chart, text page, or data grid with no technical drawing"` | → `score_table` |

The two scores are softmax-normalised so they sum to 1.  
`keep = True` when `score_drawing ≥ threshold` (default **0.60**).  
`keep = False` = flagged as non-drawing → will be skipped by `00b`.

> **Threshold guide:**  
> `0.60` (default) — conservative, keeps borderline images, low false-positive rate  
> `0.65` — moderate filtering  
> `0.70` — aggressive, only keep high-confidence drawings

---

## Outputs

Both written under `cfg["paths"]["triage"]` = `1639_DS/triage/`:

| File | Content |
|------|---------|
| `<patent_id>.json` | Per-image scores for one patent: `file`, `pred`, `score_drawing`, `score_table`, `keep` |
| `triage_summary.csv` | One row per patent: `patent_id`, `total_images`, `flagged_count`, `flagged_ratio` |

Already-processed patents are **not re-scored** on repeat runs (JSON exists → skip).

---

## Where it fits in the pipeline

```
00a    (download from PatSeer)
 ↓
00a.1  (audit: which patents are missing / need re-download)
 ↓
00a.2  ← YOU ARE HERE  (score every image: drawing vs. non-drawing)
 ↓
00b    (figure crop + _F/_Fu label matching — uses triage to skip flagged images)
 ↓
02     (pad + resize to 518×518)
```

---

## Cell guide

| Cell | What it does |
|------|--------------|
| 1 | Load config — resolves `raw_images` and `triage` paths |
| 2 | Load SigLIP model (~3 GB weights, cached after first run, needs GPU) |
| 3 | Run triage — set `limit=10` to test on 10 patents first, `limit=None` for full dataset |
| 4 | Inspect results — flagged ratio summary + per-image table for worst patents |

---

## Before you run

- **GPU required** — SigLIP ViT-SO400M is large; CPU inference is very slow (~10 s/image).  
- **First run downloads ~3 GB** of weights into the HuggingFace cache (`~/.cache/huggingface/`).  
- Run Cell 3 with `limit=10` first to check the threshold is sensible for your data before processing all 1350 folders.  
- If scores cluster around 0.50–0.52 (as in the test output above), the prompts may need tuning for your specific patent images — see `src/triage_filter.py` → `_PROMPT_KEEP` / `_PROMPT_FLAG`.

In [9]:
# Loads SigLIP ViT-SO400M-14-SigLIP-384 via open_clip.
# Downloads ~3 GB of weights on first run (cached by HuggingFace Hub).
model, processor, device = triage_filter.load_siglip_model(cfg)
print(f"SigLIP ready on: {device}")

[SigLIP] Cache: /home/vasco/Vasco Workspace/Tese_Vasco_Lnx/Patent-Labelling-Tools/models/SigLIP
[SigLIP] Loaded fp16 on cuda:0  (5.2 GB VRAM remaining)
SigLIP ready on: cuda:0

In [ ]:
# ── Run options ──────────────────────────────────────────────────────────────
TEST_MODE  = False   # True = only 10 patents (quick sanity check)
                    # False = full dataset (all ~1350 folders)
THRESHOLD  = 0.53   # kept for API compatibility; logic now uses pure argmax
                    # (discard only when model prefers the table/text prompt)
# ─────────────────────────────────────────────────────────────────────────────

limit = 600 if TEST_MODE else None
print(f"Running triage: {'TEST MODE (10 patents)' if TEST_MODE else 'FULL DATASET'}, threshold={THRESHOLD}")
triage_filter.run_triage(cfg, threshold=THRESHOLD, limit=limit)

Running triage: FULL DATASET, threshold=0.53
[SigLIP] Cache: /home/vasco/Vasco Workspace/Tese_Vasco_Lnx/Patent-Labelling-Tools/models/SigLIP
[SigLIP] Loaded fp16 on cuda:1  (4.1 GB VRAM remaining)
  ✓ AT503689A1_38777771  total=2  flagged=2
  ✓ AU2020100605A4_70776151  total=12  flagged=12
  ✓ AU2021232803A1_85775850  total=10  flagged=10
  ✓ AU2023270571A1_95939416  total=4  flagged=4
  ✓ BR112023017877B1_83067308  total=7  flagged=7
  ✓ CA2869734A1_49882410  total=10  flagged=9
  ✓ CA2874341A1_50068674  total=10  flagged=10
  ✓ CA2947683A1_62068329  total=5  flagged=5
  ✓ CA2958445A1_63166000  total=5  flagged=5
  ✓ CA2963502A1_63709012  total=2  flagged=2
  ✓ CA2967221A1_58707420  total=11  flagged=11
  ✓ CA2967228A1_58707421  total=11  flagged=11
  ✓ CA2967402A1_58709316  total=12  flagged=12
  ✓ CA3096221A1_81206876  total=41  flagged=40
  ✓ CN101885295A_43071443  total=12  flagged=11
  ✓ CN103786881A_50663046  total=12  flagged=12
  ✓ CN104229137A_52218225  total=9  flagged=9
  ✓ CN105730692A_56254804  total=5  flagged=5
  ✓ CN105799934A_56467513  total=9  flagged=9
  ✓ CN105836109A_56597035  total=4  flagged=4
  ✓ CN105836121A_56597616  total=5  flagged=5
  ✓ CN105923154A_56832133  total=2  flagged=2
  ✓ CN106005373A_57096574  total=12  flagged=12
  ✓ CN106005387A_57116011  total=6  flagged=6
  ✓ CN106043685A_57172473  total=3  flagged=3
  ✓ CN106143900A_57353415  total=3  flagged=3
  ✓ CN106218887A_57553770  total=3  flagged=3
  ✓ CN106314794A_57819675  total=7  flagged=7
  ✓ CN106494614A_58323847  total=7  flagged=7
  ✓ CN106585976A_58594339  total=7  flagged=7
  ✓ CN106628168A_58813122  total=6  flagged=6
  ✓ CN106828919A_59128637  total=3  flagged=3
  ✓ CN106828920A_59128516  total=5  flagged=5
  ✓ CN106864746A_59166843  total=3  flagged=3
  ✓ CN106882372A_59180265  total=5  flagged=5
  ✓ CN106882373A_59179679  total=7  flagged=7
  ✓ CN106927040A_59423690  total=3  flagged=3
  ✓ CN106938701A_59469510  total=3  flagged=3
  ✓ CN106965928A_59329348  total=3  flagged=3
  ✓ CN107010180A_59439863  total=3  flagged=3
  ✓ CN107499513A_60694792  total=8  flagged=8
  ✓ CN107521686A_60748639  total=12  flagged=12
  ✓ CN107856855A_61701792  total=3  flagged=3
  ✓ CN108163193A_62514191  total=10  flagged=10
  ✓ CN108382580A_63070285  total=3  flagged=3
  ✓ CN108394557A_63092231  total=3  flagged=3
  ✓ CN108408043A_63129567  total=6  flagged=6
  ✓ CN108502167A_63373209  total=10  flagged=10
  ✓ CN108657426A_63776108  total=2  flagged=2
  ✓ CN108674654A_63802184  total=7  flagged=5
  ✓ CN108688803A_63850917  total=9  flagged=7
  ✓ CN108706104A_63866485  total=3  flagged=3
  ✓ CN108750103A_64021047  total=7  flagged=7
  ✓ CN108791876A_64069836  total=7  flagged=6
  ✓ CN108928471A_64445223  total=4  flagged=4
  ✓ CN109080824A_64794656  total=5  flagged=5
  ✓ CN109159890A_64876160  total=5  flagged=5
  ✓ CN109250104A_65043046  total=5  flagged=5
  ✓ CN109263898A_65195149  total=5  flagged=5
  ✓ CN109263903A_65194081  total=3  flagged=3
  ✓ CN109263905A_65195087  total=4  flagged=4
  ✓ CN109263907A_65195107  total=5  flagged=5
  ✓ CN109263908A_65195091  total=5  flagged=5
  ✓ CN109263910A_65195111  total=3  flagged=3
  ✓ CN109263914A_65194224  total=3  flagged=3
  ✓ CN109263926A_65195026  total=3  flagged=3
  ✓ CN109263932A_65194174  total=3  flagged=3
  ✓ CN109263945A_65194575  total=5  flagged=5
  ✓ CN109263947A_65195536  total=4  flagged=3
  ✓ CN109263949A_65195581  total=3  flagged=3
  ✓ CN109263950A_65195607  total=5  flagged=5
  ✓ CN109263951A_65195620  total=5  flagged=5
  ✓ CN109263953A_65195611  total=6  flagged=6
  ✓ CN109263956A_65195617  total=4  flagged=3
  ✓ CN109263958A_65195597  total=6  flagged=6
  ✓ CN109263959A_65195626  total=7  flagged=7
  ✓ CN109263961A_65195213  total=4  flagged=4
  ✓ CN109263962A_65195623  total=5  flagged=5
  ✓ CN109263968A_65195038  total=4  flagged=4
  ✓ CN109263969A_65195023  total=2  flagged=2
  ✓ CN109263972A_65194142  total=6  flagged=6
  ✓ CN109263981A_65194117  total=4  flagged=4
  ✓ CN109606635A_66017023  total=6  flagged=6
  ✓ CN109649648A_66120126  total=7  flagged=7
  ✓ CN109649650A_66118263  total=5  flagged=5
  ✓ CN110040248A_67279985  total=6  flagged=6
  ✓ CN110155317A_67634276  total=3  flagged=3
  ✓ CN110282126A_68002328  total=6  flagged=6
  ✓ CN110450948A_68487714  total=5  flagged=5
  ✓ CN110450949A_68487715  total=2  flagged=2
  ✓ CN110588948A_68850154  total=5  flagged=5
  ✓ CN110626494A_68972200  total=4  flagged=4
  ✓ CN111056002A_70307649  total=6  flagged=6
  ✓ CN111137447A_70526232  total=10  flagged=10
  ✓ CN111137448A_70526233  total=12  flagged=12
  ✓ CN111137449A_70526239  total=12  flagged=12
  ✓ CN111137450A_70526335  total=12  flagged=12
  ✓ CN111137451A_70526365  total=10  flagged=10
  ✓ CN111137452A_70526339  total=10  flagged=10
  ✓ CN111232196A_70878987  total=5  flagged=5
  ✓ CN111301676A_69844594  total=12  flagged=9
  ✓ CN111532426A_71969677  total=7  flagged=7
  ✓ CN111619804A_72255834  total=7  flagged=7
  ✓ CN111731475A_72653549  total=7  flagged=7
  ✓ CN111731476A_72648791  total=9  flagged=9
  ✓ CN111762314A_72723670  total=9  flagged=9
  ✓ CN111846213A_72948100  total=10  flagged=10
  ✓ CN111874224A_73199342  total=4  flagged=4
  ✓ CN111874226A_73151682  total=11  flagged=11
  ✓ CN111891344A_73230637  total=10  flagged=10
  ✓ CN112061386A_73682875  total=7  flagged=7
  ✓ CN112124592A_73844585  total=8  flagged=8
  ✓ CN112141347A_73954358  total=5  flagged=5
  ✓ CN112478154A_74940243  total=6  flagged=6
  ✓ CN112623209A_75290300  total=8  flagged=8
  ✓ CN112896499A_76107874  total=3  flagged=0
  ✓ CN113022848A_76456796  total=9  flagged=9
  ✓ CN113086183A_76679366  total=4  flagged=4
  ✓ CN113086184A_76679591  total=7  flagged=7
  ✓ CN113247244A_77180817  total=4  flagged=4
  ✓ CN113306714A_77381678  total=12  flagged=12
  ✓ CN113335501A_77479862  total=12  flagged=12
  ✓ CN113443135A_74346821  total=7  flagged=7
  ✓ CN113460300A_77866599  total=11  flagged=11
  ✓ CN113525678A_78093370  total=5  flagged=5
  ✓ CN113716033A_78681585  total=12  flagged=12
  ✓ CN113799970A_78938278  total=9  flagged=9
  ✓ CN113844647A_78974750  total=7  flagged=7
  ✓ CN113844648A_78979179  total=12  flagged=2
  ✓ CN113998098A_79930776  total=4  flagged=4
  ✓ CN114056558A_80278975  total=7  flagged=7
  ✓ CN114180048A_80545243  total=5  flagged=5
  ✓ CN114248915A_80791501  total=3  flagged=3
  ✓ CN114394232A_81232753  total=7  flagged=7
  ✓ CN114435591A_81374329  total=11  flagged=11
  ✓ CN114449860A_81372043  total=10  flagged=10
  ✓ CN114620226A_81899069  total=11  flagged=11
  ✓ CN114684361A_82142492  total=4  flagged=4
  ✓ CN114735209A_82278637  total=5  flagged=5
  ✓ CN114802735A_82535421  total=10  flagged=10
  ✓ CN114802742A_82531591  total=7  flagged=7
  ✓ CN114954905A_82985117  total=12  flagged=12
  ✓ CN115092392A_83287530  total=7  flagged=7
  ✓ CN115180142A_83512925  total=12  flagged=12
  ✓ CN115258146A_83757607  total=11  flagged=8
  ✓ CN115285345A_83825460  total=9  flagged=6
  ✓ CN115303479A_83867082  total=11  flagged=11
  ✓ CN115447786A_84310486  total=9  flagged=9
  ✓ CN115583348A_84771519  total=12  flagged=12
  ✓ CN116215850A_86583598  total=3  flagged=3
  ✓ CN116280175A_86802222  total=2  flagged=2
  ✓ CN116280179A_86786318  total=12  flagged=12
  ✓ CN116374167A_86965726  total=7  flagged=7
  ✓ CN116443246A_87134591  total=9  flagged=9
  ✓ CN116513455A_87400372  total=6  flagged=6
  ✓ CN116692003A_87830214  total=10  flagged=10
  ✓ CN117048822A_88658269  total=9  flagged=3
  ✓ CN117184468A_89004092  total=12  flagged=12
  ✓ CN117341965A_89362694  total=11  flagged=11
  ✓ CN117360784A_89400152  total=12  flagged=12
  ✓ CN117465666A_89624985  total=9  flagged=9
  ✓ CN117465668A_89639513  total=7  flagged=7
  ✓ CN117566089A_89894246  total=10  flagged=10
  ✓ CN117682065A_90135464  total=3  flagged=3
  ✓ CN117799494A_90431947  total=4  flagged=4
  ✓ CN117842351A_90542130  total=10  flagged=10
  ✓ CN117985223A_90897714  total=11  flagged=9
  ✓ CN118025467A_90982835  total=6  flagged=6
  ✓ CN118083120A_91143746  total=11  flagged=11
  ✓ CN118124795A_91231148  total=9  flagged=9
  ✓ CN118323437A_91770425  total=8  flagged=8
  ✓ CN118343291A_91813832  total=12  flagged=10
  ✓ CN118439173A_92319228  total=6  flagged=6
  ✓ CN118457914A_92156665  total=10  flagged=10
  ✓ CN118494752A_92240808  total=12  flagged=12
  ✓ CN118618608A_92601088  total=12  flagged=12
  ✓ CN118701285A_92811088  total=7  flagged=7
  ✓ CN118723072A_92853893  total=5  flagged=5
  ✓ CN118723073A_92861725  total=8  flagged=8
  ✓ CN118770544A_92984157  total=4  flagged=1
  ✓ CN118770545A_92996907  total=8  flagged=3
  ✓ CN118811082A_93068608  total=3  flagged=3
  ✓ CN118877199A_93227783  total=5  flagged=5
  ✓ CN118992092A_93474531  total=3  flagged=3
  ✓ CN119018344A_93527803  total=7  flagged=7
  ✓ CN119099860A_93717638  total=12  flagged=12
  ✓ CN119190349A_94058635  total=10  flagged=10
  ✓ CN119190372A_94061817  total=12  flagged=12
  ✓ CN119190373A_94076509  total=12  flagged=12
  ✓ CN119218412A_94040782  total=12  flagged=12
  ✓ CN119218413A_94069178  total=12  flagged=12
  ✓ CN119218430A_94068930  total=12  flagged=12
  ✓ CN119218431A_94048691  total=12  flagged=12
  ✓ CN119218432A_93946987  total=12  flagged=12
  ✓ CN119218433A_94070641  total=12  flagged=12
  ✓ CN119231792A_93946991  total=12  flagged=12
  ✓ CN119231793A_94070640  total=12  flagged=12
  ✓ CN119231794A_93945313  total=12  flagged=12
  ✓ CN119239921A_94035552  total=12  flagged=12
  ✓ CN119239928A_94035694  total=9  flagged=6
  ✓ CN119239935A_94032581  total=11  flagged=11
  ✓ CN119239958A_94018389  total=12  flagged=12
  ✓ CN119262274A_94112956  total=12  flagged=12
  ✓ CN119262283A_94107470  total=6  flagged=6
  ✓ CN119262284A_94110123  total=8  flagged=8
  ✓ CN119460096A_94582017  total=6  flagged=6
  ✓ CN119460097A_94575479  total=5  flagged=5
  ✓ CN119489922A_94628350  total=5  flagged=5
  ✓ CN119568404A_94796479  total=7  flagged=7
  ✓ CN119611751A_94888679  total=4  flagged=4
  ✓ CN119611752A_94907377  total=7  flagged=3
  ✓ CN119872875A_95436262  total=12  flagged=12
  ✓ CN120024492A_95735420  total=11  flagged=11
  ✓ CN120033940A_95736108  total=9  flagged=9
  ✓ CN120096806A_95877323  total=5  flagged=5
  ✓ CN120096807A_95888217  total=5  flagged=5
  ✓ CN120135432A_95951004  total=5  flagged=5
  ✓ CN120171750A_96042187  total=8  flagged=8
  ✓ CN120191516A_96063272  total=12  flagged=12
  ✓ CN120229361A_96157381  total=8  flagged=8
  ✓ CN120270494A_96243410  total=7  flagged=5
  ✓ CN120270503A_96245444  total=12  flagged=12
  ✓ CN120288238A_96267548  total=12  flagged=12
  ✓ CN120397241A_96504638  total=9  flagged=8
  ✓ CN120397245A_96510287  total=11  flagged=11
  ✓ CN120423050A_96563021  total=3  flagged=3
  ✓ CN120482345A_96675626  total=12  flagged=12
  ✓ CN120503960A_96714318  total=5  flagged=5
  ✓ CN120517586A_96742899  total=12  flagged=12
  ✓ CN120697951A_97109777  total=9  flagged=9
  ✓ CN120716940A_97161145  total=12  flagged=12
  ✓ CN120735960A_97182431  total=12  flagged=12
  ✓ CN120735961A_97198381  total=9  flagged=9
  ✓ CN120793159A_97308918  total=6  flagged=6
  ✓ CN120817242A_97375279  total=8  flagged=8
  ✓ CN120828942A_97399306  total=9  flagged=9
  ✓ CN120863861A_97470266  total=6  flagged=6
  ✓ CN120863865A_97459321  total=10  flagged=8
  ✓ CN120863869A_97470200  total=6  flagged=6
  ✓ CN120887008A_97503485  total=7  flagged=7
  ✓ CN120922344A_97594394  total=12  flagged=12
  ✓ CN120922349A_97583461  total=8  flagged=8
  ✓ CN121158211A_98041733  total=8  flagged=8
  ✓ CN121224978A_98148467  total=6  flagged=6
  ✓ CN121376154A_98460140  total=12  flagged=12
  ✓ CN121448607A_98587661  total=8  flagged=5
  ✓ CN121530138A_98711939  total=11  flagged=11
  ✓ CN121650868A_98986873  total=9  flagged=9
  ✓ CN121671872A_99028991  total=12  flagged=12
  ✓ CN121822815A_99339917  total=7  flagged=7
  ✓ CN121871769A_99419901  total=12  flagged=12
  ✓ CN202728574U_47654301  total=7  flagged=7
  ✓ CN206511122U_59867587  total=5  flagged=5
  ✓ CN218288104U_84809563  total=12  flagged=6
  ✓ CZ2023513A3_96171384  total=11  flagged=11
  ✓ DE102007055313A1_40576821  total=11  flagged=10
  ✓ DE102008044812A1_40530774  total=1  flagged=1
  ✓ DE102012020498A1_50436711  total=6  flagged=6
  ✓ DE102013001852A1_51163257  total=2  flagged=2
  ✓ DE102015000703A1_56293457  total=4  flagged=4
  ✓ DE102015017425B3_85284263  total=12  flagged=12
  ✓ DE102015105976A1_57043797  total=4  flagged=4
  ✓ DE102016001771A1_57630429  total=7  flagged=7
  ✓ DE102016011273A1_61301942  total=3  flagged=3
  ✓ DE102016015461A1_59010570  total=4  flagged=4
  ✓ DE102017122359A1_63914990  total=5  flagged=4
  ✓ DE102017123536A1_65817278  total=3  flagged=3
  ✓ DE102018100230A1_66995223  total=5  flagged=5
  ✓ DE102018113265A1_68576139  total=6  flagged=4
  ✓ DE102018116149A1_68943504  total=2  flagged=2
  ✓ DE102018116150A1_68943533  total=2  flagged=2
  ✓ DE102018116151A1_68943534  total=2  flagged=2
  ✓ DE102018116153A1_68943509  total=5  flagged=5
  ✓ DE102018116154A1_68943485  total=3  flagged=3
  ✓ DE102018116155A1_68943481  total=3  flagged=3
  ✓ DE102018116157A1_68943517  total=2  flagged=2
  ✓ DE102018116158A1_68943520  total=2  flagged=2
  ✓ DE102018116160A1_68943540  total=2  flagged=2
  ✓ DE102018116161A1_68943523  total=3  flagged=3
  ✓ DE102018116165A1_68943541  total=2  flagged=2
  ✓ DE102018116166A1_68943542  total=3  flagged=3
  ✓ DE102018116170A1_68943547  total=2  flagged=2
  ✓ DE102018116172A1_68943552  total=2  flagged=2
  ✓ DE102018123470A1_69725547  total=6  flagged=6
  ✓ DE102018130822A1_70681344  total=2  flagged=2
  ✓ DE102019001240A1_71843474  total=4  flagged=4
  ✓ DE102019001834A1_72240932  total=11  flagged=11
  ✓ DE102019004808A1_74092519  total=3  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ DE102019006484B3_71615573  total=12  flagged=12
  ✓ DE102019007020A1_75156016  total=12  flagged=12
  ✓ DE102019009187A1_73747659  total=1  flagged=1
  ✓ DE102019101358A1_71402602  total=1  flagged=1
  ✓ DE102019101359A1_71403069  total=4  flagged=4
  ✓ DE102019101362A1_71402646  total=3  flagged=3
  ✓ DE102019102189A1_67224462  total=5  flagged=4
  ✓ DE102019118023B3_71402838  total=5  flagged=5
  ✓ DE102019118024A1_74092679  total=2  flagged=2
  ✓ DE102019121788A1_74239987  total=2  flagged=2
  ✓ DE102020007834A1_81847393  total=8  flagged=8
  ✓ DE102020007836A1_81847214  total=8  flagged=8
  ✓ DE102020107437A1_77552521  total=3  flagged=3
  ✓ DE102020113488A1_78408629  total=12  flagged=12
  ✓ DE102020118674A1_79020761  total=3  flagged=3
  ✓ DE102020118677A1_79020751  total=2  flagged=2
  ✓ DE102020202612A1_73790105  total=4  flagged=4
  ✓ DE102021113538A1_81851524  total=3  flagged=3
  ✓ DE102023108565B3_89508163  total=6  flagged=6
  ✓ DE102023122141A1_94391001  total=2  flagged=2
  ✓ DE102023122145A1_94391062  total=3  flagged=3
  ✓ DE102023122146A1_94391408  total=4  flagged=4
  ✓ DE102023129326A1_95342019  total=3  flagged=3
  ✓ DE102023130037B3_91852679  total=2  flagged=2
  ✓ DE102023133781B3_94170746  total=3  flagged=3
  ✓ DE102023135708A1_93650362  total=7  flagged=4
  ✓ DE102024102439A1_96347327  total=3  flagged=3
  ✓ DE102024102441A1_96347471  total=3  flagged=3
  ✓ DE102024103065B3_96020776  total=4  flagged=4
  ✓ DE102024103232A1_96431667  total=7  flagged=7
  ✓ DE102024103420A1_96431625  total=5  flagged=5
  ✓ DE102024104137A1_96499238  total=5  flagged=5
  ✓ DE102024104138A1_96499224  total=5  flagged=5
  ✓ DE102024105430A1_96659127  total=2  flagged=2
  ✓ DE102024105438A1_96659019  total=3  flagged=3
  ✓ DE102024105439A1_96659041  total=5  flagged=5
  ✓ DE102024105440A1_96659522  total=3  flagged=3
  ✓ DE102024105441A1_96659189  total=2  flagged=2
  ✓ DE102024105446A1_96658943  total=3  flagged=3
  ✓ DE102024105448A1_96659245  total=2  flagged=2
  ✓ DE102024105449A1_96659500  total=4  flagged=4
  ✓ DE102024105450A1_96658937  total=4  flagged=4
  ✓ DE102024105452A1_96659133  total=5  flagged=5
  ✓ DE102024106633A1_96810519  total=9  flagged=9
  ✓ DE102024122189A1_98433859  total=11  flagged=11
  ✓ DE102024127443A1_98977501  total=3  flagged=3
  ✓ DE202008012643U1_40157972  total=3  flagged=3
  ✓ DE202013011072U1_50098871  total=1  flagged=1
  ✓ DE202013011452U1_50383557  total=3  flagged=3
  ✓ DE202014004877U1_51349878  total=3  flagged=3
  ✓ DE202015007089U1_54768325  total=1  flagged=1
  ✓ DE202016005012U1_57110400  total=1  flagged=1
  ✓ DE202018002525U1_62983090  total=6  flagged=6
  ✓ DE202018104519U1_68053281  total=6  flagged=4
  ✓ DE202018104722U1_63587890  total=1  flagged=1
  ✓ DE202019000936U1_66335505  total=3  flagged=3
  ✓ DE202019001820U1_67848556  total=2  flagged=2
  ✓ DE202019002731U1_67622690  total=7  flagged=7
  ✓ DE202020000096U1_70546105  total=1  flagged=1
  ✓ DE202020005116U1_74846132  total=5  flagged=5
  ✓ DE202023102941U1_92713002  total=11  flagged=9
  ✓ DE202024002149U1_94391509  total=8  flagged=8
  ✓ DE202024104657U1_94391467  total=4  flagged=4
  ✓ DE202024104658U1_94391535  total=3  flagged=2
  ✓ EP2570345A1_46924211  total=5  flagged=5
  ✓ EP2669195A1_48537748  total=12  flagged=12
  ✓ EP3119674A2_57588805  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ EP3290334A1_59745849  total=12  flagged=12
  ✓ EP3360780A1_61132051  total=12  flagged=10
  ✓ EP3453616A1_63293968  total=12  flagged=11
  ✓ EP3594113A1_63449420  total=10  flagged=10
  ✓ EP3636545A1_68242353  total=12  flagged=12
  ✓ EP3770063A1_67851083  total=8  flagged=8
  ✓ EP3805100A1_68242276  total=8  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ EP3907132A1_70680379  total=8  flagged=8
  ✓ EP3974315A1_72659736  total=6  flagged=6
  ✓ EP3998191A1_74672189  total=7  flagged=6
  ✓ EP3998195A1_74672222  total=5  flagged=5
  ✓ EP3998199A1_74672090  total=6  flagged=6
  ✓ EP3998206A1_74672197  total=8  flagged=8
  ✓ EP3998209A1_74859722  total=12  flagged=12
  ✓ EP4134301A1_77316847  total=6  flagged=5
  ✓ EP4151521A1_78695660  total=8  flagged=8
  ✓ EP4155193A1_77913035  total=7  flagged=6
  ✓ EP4230518A1_80445889  total=6  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ EP4303124A1_82850459  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ EP4306409A1_82594614  total=3  flagged=2

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ EP4339109A1_83593899  total=8  flagged=8
  ✓ EP4361026A1_84043779  total=7  flagged=6
  ✓ EP4417511A1_85285234  total=8  flagged=4
  ✓ EP4434880A1_85726750  total=7  flagged=7
  ✓ EP4467450A1_87196346  total=13  flagged=13
  ✓ EP4506770A1_87567469  total=12  flagged=8
  ✓ EP4545416A1_88511180  total=6  flagged=5
  ✓ EP4559808A1_88923633  total=6  flagged=6
  ✓ EP4563464A1_93741590  total=13  flagged=12
  ✓ EP4653315A1_91924121  total=11  flagged=11
  ✓ EP4653316A1_91924208  total=11  flagged=11
  ✓ EP4717605A1_90363660  total=9  flagged=8
  ✓ EP4741286A1_93455580  total=8  flagged=8
  ✓ EP4748710A1_94476356  total=10  flagged=10
  ✓ EP4748711A1_94383019  total=12  flagged=12
  ✓ EP4749890A1_97563936  total=12  flagged=12
  ✓ ES1291103U_81706521  total=2  flagged=2
  ✓ ES2288083A1_38787093  total=8  flagged=8
  ✓ ES2289903A1_38961544  total=2  flagged=2
  ✓ ES2317764A1_40513476  total=1  flagged=1
  ✓ ES2349098A1_43415152  total=4  flagged=4
  ✓ ES2555162A1_54883777  total=1  flagged=1
  ✓ ES2604711A1_58191740  total=1  flagged=1
  ✓ ES2775773A1_71729122  total=12  flagged=12
  ✓ FR2830237A1_8867702  total=3  flagged=2
  ✓ FR2942455A1_42557021  total=5  flagged=4
  ✓ FR2955559A1_42651204  total=6  flagged=6
  ✓ FR2980171A1_45757474  total=12  flagged=12
  ✓ FR2993245A1_46940535  total=1  flagged=1
  ✓ FR2997924A1_47741044  total=3  flagged=3
  ✓ FR3018768A1_50829035  total=5  flagged=5
  ✓ FR3033363A1_53404613  total=4  flagged=4
  ✓ FR3037038A1_54545172  total=2  flagged=2
  ✓ FR3041930A1_55361533  total=3  flagged=3
  ✓ FR3071480A1_65859711  total=11  flagged=10
  ✓ FR3074779A1_61028020  total=5  flagged=5
  ✓ FR3092083A1_67185245  total=2  flagged=2
  ✓ FR3096959A1_68343003  total=2  flagged=2
  ✓ FR3101328A1_69375455  total=2  flagged=2
  ✓ FR3104333A1_69903398  total=2  flagged=2
  ✓ FR3106572A1_69811406  total=5  flagged=5
  ✓ FR3111872A1_74095847  total=2  flagged=2
  ✓ FR3115264A1_74347237  total=2  flagged=2
  ✓ FR3115265A1_74347238  total=2  flagged=2
  ✓ FR3115266A1_74592074  total=2  flagged=2
  ✓ FR3119159A1_75690391  total=2  flagged=2
  ✓ FR3127478A1_80225585  total=2  flagged=2
  ✓ FR3136745A1_83996810  total=2  flagged=2
  ✓ FR3143549A1_86007682  total=2  flagged=2
  ✓ FR3146308A1_87280542  total=2  flagged=2
  ✓ FR3158709A1_91247625  total=2  flagged=2
  ✓ FR3159149A1_91335035  total=2  flagged=2
  ✓ GB201303910D0_48142435  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ GB201307739D0_48627027  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ GB201307770D0_48627052  total=4  flagged=4
  ✓ GB201502495D0_52781619  total=3  flagged=3
  ✓ GB201721835D0_61131560  total=9  flagged=9
  ✓ GB201721837D0_61131622  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ GB201801059D0_61283657  total=5  flagged=5

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ GB201801766D0_61730906  total=4  flagged=1
  ✓ GB201806772D0_62236143  total=7  flagged=7
  ✓ GB201903200D0_66380275  total=5  flagged=5
  ✓ GB202006780D0_71134956  total=6  flagged=6
  ✓ GB202006781D0_71134839  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ GB202210440D0_84540139  total=12  flagged=12
  ✓ GB202302628D0_85793928  total=12  flagged=11
  ✓ GB202302720D0_85793925  total=11  flagged=11
  ✓ GB202306162D0_86605496  total=8  flagged=6
  ✓ GB202311251D0_87852126  total=8  flagged=7
  ✓ GB202313751D0_88412872  total=12  flagged=12
  ✓ GB202313753D0_88412696  total=12  flagged=12
  ✓ GB202410204D0_92458746  total=3  flagged=3
  ✓ GB202410221D0_92458823  total=12  flagged=12
  ✓ GB202415968D0_93743348  total=12  flagged=12
  ✓ IN202011031027A_72202011031027  total=5  flagged=5
  ✓ IT201900011040A1_68501895  total=6  flagged=6
  ✓ IT202100023033A1_78649894  total=7  flagged=7
  ✓ IT202200018594A1_84359689  total=9  flagged=9
  ✓ IT202300024612A1_89897947  total=3  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ ITPI20130073A1_49519050  total=7  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ ITTO20130495A1_49085162  total=7  flagged=6
  ✓ ITUB20150829A1_53901004  total=11  flagged=10
  ✓ JP2014213846A_51940008  total=3  flagged=3
  ✓ JP2023526056A_60002023526056  total=12  flagged=12
  ✓ JP2024519073A_60002024519073  total=12  flagged=12
  ✓ JP7438589B1_90011450  total=8  flagged=8
  ✓ KR100555176B1_37179218  total=12  flagged=12
  ✓ KR100822366B1_39571552  total=11  flagged=11
  ✓ KR100832067B1_39665122  total=3  flagged=3
  ✓ KR101129249B1_46607088  total=7  flagged=7
  ✓ KR101749863B1_59282852  total=7  flagged=7
  ✓ KR101813681B1_61070316  total=11  flagged=11
  ✓ KR102164227B1_72886441  total=12  flagged=12
  ✓ KR102211475B1_74559535  total=10  flagged=10
  ✓ KR102622742B1_89533015  total=12  flagged=12
  ✓ KR102712524B1_93117104  total=10  flagged=10
  ✓ KR102760903B1_94612113  total=9  flagged=9
  ✓ KR20050016643A_41783551  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ KR20060074923A_37167543  total=1  flagged=1
  ✓ KR20060079414A_37171053  total=4  flagged=4
  ✓ KR20060094937A_37602565  total=12  flagged=12
  ✓ KR20100094056A_42758287  total=5  flagged=5
  ✓ KR20110127560A_45396178  total=6  flagged=6
  ✓ KR20130031490A_48180625  total=11  flagged=11
  ✓ KR20130083961A_48994747  total=12  flagged=12
  ✓ KR20160031602A_55645015  total=6  flagged=6
  ✓ KR20160120094A_57250409  total=6  flagged=6
  ✓ KR20170030407A_58502248  total=7  flagged=7
  ✓ KR20190059174A_66675876  total=8  flagged=8
  ✓ KR20190119712A_68460770  total=9  flagged=9
  ✓ KR20200079649A_71571440  total=12  flagged=9
  ✓ KR20210059370A_76145537  total=8  flagged=8
  ✓ KR20220017042A_80266315  total=12  flagged=12
  ✓ KR20220033079A_80937728  total=12  flagged=12
  ✓ KR20230075012A_86542877  total=6  flagged=6
  ✓ KR20230089903A_86989656  total=11  flagged=11
  ✓ KR20240080620A_91480079  total=4  flagged=4
  ✓ KR20240170008A_93847180  total=12  flagged=12
  ✓ KR20250038333A_95205843  total=11  flagged=11
  ✓ KR20250121294A_96733921  total=12  flagged=12
  ✓ KR20260072583A_84020260072583  total=41  flagged=40

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ NL2019667B1_64661429  total=9  flagged=9
  ✓ PT109064A_59579337  total=11  flagged=10
  ✓ RO131684A0_58093839  total=6  flagged=6
  ✓ RU180474U1_62619630  total=7  flagged=7
  ✓ RU189830U1_66792710  total=5  flagged=5
  ✓ RU192967U1_68162677  total=3  flagged=3

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ RU2015128842A_57758323  total=4  flagged=4
  ✓ RU2015135410A_58453840  total=6  flagged=6
  ✓ RU2018102765A_67513055  total=8  flagged=8
  ✓ RU2018115530A_68500204  total=12  flagged=12
  ✓ RU2018121419A_68834286  total=4  flagged=4
  ✓ RU2018140767A_70734813  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ RU2577931C1_55648085  total=2  flagged=2
  ✓ RU2641952C1_61023785  total=3  flagged=3
  ✓ RU2657650C1_62620090  total=7  flagged=7
  ✓ RU2670361C1_63923480  total=10  flagged=10
  ✓ RU2681464C1_65632802  total=5  flagged=4
  ✓ RU2698276C1_67733939  total=5  flagged=5
  ✓ RU2700154C1_67989562  total=6  flagged=6
  ✓ RU2701284C1_68063557  total=5  flagged=5
  ✓ RU2711768C1_69184024  total=4  flagged=4
  ✓ RU2725833C1_71510455  total=4  flagged=4
  ✓ RU2727787C1_71741321  total=4  flagged=2
  ✓ RU2729750C1_72086323  total=1  flagged=1
  ✓ RU2730745C1_72238031  total=10  flagged=10
  ✓ RU2755561C1_77745520  total=9  flagged=8
  ✓ RU2757693C1_78286650  total=12  flagged=12
  ✓ RU2759060C1_78466873  total=4  flagged=4
  ✓ RU2759061C1_78466891  total=9  flagged=9
  ✓ RU2762441C1_80039043  total=8  flagged=8
  ✓ RU2762906C1_80039133  total=4  flagged=4
  ✓ RU2764311C1_80040360  total=6  flagged=4
  ✓ SK500442018A3_68393052  total=6  flagged=6
  ✓ TWI627104B_62386186  total=12  flagged=8
  ✓ UA124132C2_76865258  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ UA151311U_82404778  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ UA152017U_89902489  total=4  flagged=4

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10017247B1_62750261  total=6  flagged=6

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10053213B1_62142993  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10144503B1_64451753  total=12  flagged=12
  ✓ US10167076B1_64736539  total=7  flagged=7
  ✓ US10301008B1_66636453  total=5  flagged=5
  ✓ US10418868B1_67908946  total=8  flagged=8
  ✓ US10421540B1_60001758  total=7  flagged=7
  ✓ US10435145B1_68108710  total=12  flagged=12
  ✓ US10444093B1_68165195  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10450062B1_68242128  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10450063B1_68242087  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10479482B1_68536356  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US10501173B1_68766061  total=5  flagged=5
  ✓ US10526079B1_69058765  total=9  flagged=9
  ✓ US10562608B1_69528282  total=10  flagged=10
  ✓ US10589838B1_69779009  total=10  flagged=10
  ✓ US10913529B1_74537066  total=12  flagged=12
  ✓ US11001377B1_75846002  total=9  flagged=9
  ✓ US11072423B1_76971454  total=12  flagged=12
  ✓ US11077937B1_77063283  total=12  flagged=10
  ✓ US11124286B1_77749153  total=12  flagged=12
  ✓ US11208206B1_79168222  total=8  flagged=8
  ✓ US11319064B1_81380637  total=12  flagged=12
  ✓ US11449078B1_83286317  total=8  flagged=8
  ✓ US11465737B1_83547212  total=12  flagged=12
  ✓ US11472538B1_83603712  total=6  flagged=6
  ✓ US11485488B1_83809387  total=12  flagged=12
  ✓ US11548621B1_84810682  total=11  flagged=11
  ✓ US11643196B1_86242413  total=6  flagged=5
  ✓ US11673662B1_86701325  total=12  flagged=11
  ✓ US11688723B1_86899026  total=12  flagged=12
  ✓ US11691709B1_86993171  total=12  flagged=11
  ✓ US11691744B1_86993180  total=6  flagged=5
  ✓ US11697495B1_87070627  total=9  flagged=9
  ✓ US11745890B1_87882406  total=9  flagged=9
  ✓ US11772788B1_88196009  total=12  flagged=12
  ✓ US11780576B1_88242423  total=12  flagged=12
  ✓ US11787551B1_88309302  total=12  flagged=12
  ✓ US11807382B1_88649710  total=8  flagged=8
  ✓ US11811276B1_88649937  total=12  flagged=12
  ✓ US12006989B1_91382768  total=11  flagged=10
  ✓ US12091167B1_92716119  total=12  flagged=12
  ✓ US12202600B1_94282923  total=12  flagged=9
  ✓ US12227299B1_94610740  total=12  flagged=12
  ✓ US12291327B1_95563743  total=11  flagged=11
  ✓ US12312080B1_95823600  total=4  flagged=4
  ✓ US12325540B1_89898199  total=10  flagged=8
  ✓ US12377973B1_96587791  total=9  flagged=8
  ✓ US12420923B1_93314042  total=12  flagged=12
  ✓ US12486026B1_97879582  total=7  flagged=7
  ✓ US12503223B1_98223577  total=10  flagged=10
  ✓ US12559227B1_98829969  total=12  flagged=11
  ✓ US12570400B1_99012509  total=12  flagged=9
  ✓ US12600459B1_99440105  total=12  flagged=10
  ✓ US2002100834A1_26951040  total=12  flagged=12
  ✓ US2002100835A1_3827470  total=12  flagged=12
  ✓ US2002154996A1_26705128  total=12  flagged=12
  ✓ US2003085319A1_27493969  total=12  flagged=12
  ✓ US2004025490A1_31499647  total=12  flagged=12
  ✓ US2004026563A1_33563608  total=12  flagged=11
  ✓ US2004069901A1_22756957  total=12  flagged=12
  ✓ US2004129833A1_11459538  total=7  flagged=7
  ✓ US2004155143A1_23135826  total=12  flagged=12
  ✓ US2004232279A1_33450313  total=9  flagged=9
  ✓ US2005017127A1_34079630  total=11  flagged=11
  ✓ US2005061910A1_27762744  total=3  flagged=3
  ✓ US2005127238A1_34657098  total=9  flagged=9
  ✓ US2005178879A1_34837757  total=4  flagged=4
  ✓ US2005223694A1_27665376  total=5  flagged=5
  ✓ US2005230519A1_35095296  total=6  flagged=6
  ✓ US2005230520A1_3836862  total=11  flagged=11
  ✓ US2006016929A1_35656111  total=6  flagged=6
  ✓ US2006038061A1_36148747  total=12  flagged=12
  ✓ US2006054736A1_36969823  total=9  flagged=9
  ✓ US2006113426A1_31495862  total=12  flagged=12
  ✓ US2006151666A1_36652344  total=11  flagged=11
  ✓ US2006192046A1_36141977  total=7  flagged=7
  ✓ US2006192047A1_36710041  total=12  flagged=12
  ✓ US2006198732A1_33154123  total=3  flagged=3
  ✓ US2006202081A1_46322670  total=12  flagged=12
  ✓ US2006239824A1_32823163  total=7  flagged=7
  ✓ US2007158494A1_31503581  total=12  flagged=12
  ✓ US2007205326A1_39402160  total=4  flagged=4
  ✓ US2007221779A1_34909592  total=12  flagged=12
  ✓ US2008054121A1_39150154  total=12  flagged=12
  ✓ US2008169375A1_37053048  total=12  flagged=11
  ✓ US2008173769A1_39640291  total=5  flagged=5
  ✓ US2008240920A1_33535776  total=5  flagged=5
  ✓ US2008243313A1_39713981  total=5  flagged=5
  ✓ US2008272226A1_39540404  total=7  flagged=7
  ✓ US2008283673A1_36647872  total=12  flagged=12
  ✓ US2008292468A1_38256747  total=12  flagged=12
  ✓ US2009008499A1_40075709  total=11  flagged=11
  ✓ US2009008510A1_38037471  total=7  flagged=7
  ✓ US2009016877A1_39595972  total=11  flagged=11
  ✓ US2009084890A1_38191853  total=5  flagged=5
  ✓ US2009127379A1_36647957  total=10  flagged=10
  ✓ US2009140095A1_40674737  total=4  flagged=4
  ✓ US2009212166A1_39787926  total=7  flagged=7
  ✓ US2009218438A1_31991310  total=9  flagged=9
  ✓ US2009224096A1_41052615  total=9  flagged=9
  ✓ US2009256026A1_41162269  total=6  flagged=6
  ✓ US2009261209A1_38269095  total=12  flagged=12
  ✓ US2009266941A1_41214046  total=5  flagged=5
  ✓ US2009266942A1_39645003  total=4  flagged=4
  ✓ US2009283644A1_39855065  total=4  flagged=4
  ✓ US2010001143A1_41463611  total=8  flagged=8
  ✓ US2010051740A1_41723862  total=12  flagged=12
  ✓ US2010051753A1_39468355  total=12  flagged=12
  ✓ US2010072325A1_42036641  total=5  flagged=5
  ✓ US2010171001A1_42198440  total=8  flagged=8
  ✓ US2010264256A1_42980278  total=12  flagged=12
  ✓ US2010270419A1_40795959  total=12  flagged=12
  ✓ US2010270435A1_39609176  total=3  flagged=3
  ✓ US2010276549A1_39788775  total=4  flagged=4
  ✓ US2010301158A1_40886371  total=2  flagged=2
  ✓ US2011001001A1_40913336  total=12  flagged=12
  ✓ US2011001020A1_43412095  total=5  flagged=5
  ✓ US2011024552A1_43526078  total=5  flagged=4
  ✓ US2011031355A1_43534097  total=8  flagged=7
  ✓ US2011042510A1_43604537  total=12  flagged=12
  ✓ US2011163199A1_39637816  total=12  flagged=12
  ✓ US2011168835A1_44257785  total=6  flagged=6
  ✓ US2011194934A1_44356238  total=12  flagged=12
  ✓ US2011217163A1_44531481  total=9  flagged=9
  ✓ US2011259687A1_42269088  total=9  flagged=9
  ✓ US2011303795A1_56291239  total=7  flagged=7
  ✓ US2011315809A1_47883631  total=12  flagged=12
  ✓ US2012012692A1_45497427  total=8  flagged=8
  ✓ US2012049009A1_45695835  total=12  flagged=12
  ✓ US2012056040A1_40639929  total=12  flagged=12
  ✓ US2012061509A1_43126417  total=5  flagged=5
  ✓ US2012061526A1_43126416  total=4  flagged=3
  ✓ US2012063897A1_43126414  total=5  flagged=5
  ✓ US2012091257A1_42263722  total=10  flagged=9
  ✓ US2012119016A1_46046924  total=12  flagged=12
  ✓ US2012199699A1_45558617  total=11  flagged=11
  ✓ US2012211608A1_42077515  total=7  flagged=7
  ✓ US2012234968A1_46827703  total=10  flagged=9
  ✓ US2012261523A1_47005722  total=12  flagged=11
  ✓ US2012298789A1_45773779  total=9  flagged=9
  ✓ US2012318908A1_47352908  total=4  flagged=4
  ✓ US2013020429A1_47555117  total=7  flagged=6
  ✓ US2013026302A1_46142159  total=4  flagged=4
  ✓ US2013026303A1_45063079  total=11  flagged=10
  ✓ US2013026304A1_45092316  total=11  flagged=10
  ✓ US2013026305A1_44925466  total=12  flagged=11
  ✓ US2013035808A1_44196181  total=5  flagged=4
  ✓ US2013082135A1_46801287  total=1  flagged=1
  ✓ US2013092799A1_48140344  total=9  flagged=6
  ✓ US2013099065A1_44541344  total=7  flagged=7
  ✓ US2013112804A1_44904126  total=12  flagged=11
  ✓ US2013118856A1_48279558  total=5  flagged=5
  ✓ US2013121827A1_45400986  total=7  flagged=7
  ✓ US2013140405A1_48523311  total=11  flagged=11
  ✓ US2013149151A1_45444559  total=12  flagged=11
  ✓ US2013164129A1_45811330  total=8  flagged=8
  ✓ US2013264429A1_46000207  total=7  flagged=4
  ✓ US2013306802A1_48430087  total=12  flagged=12
  ✓ US2014008498A1_44800986  total=7  flagged=7
  ✓ US2014084114A1_50337921  total=11  flagged=11
  ✓ US2014110533A1_47424268  total=12  flagged=12
  ✓ US2014124613A1_45690046  total=12  flagged=12
  ✓ US2014138477A1_48781750  total=9  flagged=9
  ✓ US2014158815A1_50879887  total=12  flagged=11
  ✓ US2014158816A1_50879888  total=12  flagged=8
  ✓ US2014175214A1_50973533  total=12  flagged=12
  ✓ US2014263822A1_51523277  total=3  flagged=3
  ✓ US2014263854A1_48444095  total=12  flagged=12
  ✓ US2014263855A1_48444096  total=9  flagged=9
  ✓ US2014271180A1_48444262  total=11  flagged=11
  ✓ US2014321968A1_48741027  total=6  flagged=6
  ✓ US2014339354A1_51895012  total=11  flagged=11
  ✓ US2014360830A1_52009426  total=12  flagged=12
  ✓ US2015014475A1_52276366  total=12  flagged=11
  ✓ US2015028151A1_52389667  total=12  flagged=8
  ✓ US2015028155A1_45930023  total=5  flagged=5
  ✓ US2015048213A1_50349532  total=12  flagged=12
  ✓ US2015053826A1_49161167  total=9  flagged=9
  ✓ US2015166175A1_50478459  total=5  flagged=5
  ✓ US2015175260A1_49080841  total=7  flagged=5
  ✓ US2015191243A1_49916084  total=12  flagged=12
  ✓ US2015197337A1_51261881  total=12  flagged=12
  ✓ US2015225079A1_53774285  total=12  flagged=12
  ✓ US2015251749A1_54016621  total=5  flagged=5
  ✓ US2015266571A1_54141359  total=12  flagged=11
  ✓ US2015274290A1_54189271  total=11  flagged=10
  ✓ US2015284079A1_54209073  total=10  flagged=10
  ✓ US2015295105A1_47002500  total=10  flagged=10
  ✓ US2015314865A1_48237003  total=7  flagged=6
  ✓ US2015344134A1_54700893  total=12  flagged=11
  ✓ US2015360774A1_54835505  total=12  flagged=12
  ✓ US2015361923A1_47758026  total=12  flagged=12
  ✓ US2015375860A1_54929679  total=10  flagged=10
  ✓ US2016009376A1_55067013  total=5  flagged=5
  ✓ US2016009387A1_55067015  total=7  flagged=7
  ✓ US2016023754A1_54866841  total=12  flagged=12
  ✓ US2016026190A1_55166717  total=9  flagged=9
  ✓ US2016031555A1_54145473  total=12  flagged=12
  ✓ US2016031556A1_55179237  total=12  flagged=12
  ✓ US2016083060A1_54545564  total=12  flagged=12
  ✓ US2016096613A1_55632264  total=5  flagged=3
  ✓ US2016101854A1_52392625  total=4  flagged=4
  ✓ US2016114885A1_51898467  total=10  flagged=10
  ✓ US2016137298A1_55961005  total=12  flagged=12
  ✓ US2016144957A1_56009443  total=12  flagged=12
  ✓ US2016159458A1_55077616  total=4  flagged=4
  ✓ US2016159468A1_54703900  total=12  flagged=12
  ✓ US2016167780A1_49182418  total=10  flagged=7
  ✓ US2016200434A1_55070897  total=9  flagged=9
  ✓ US2016200436A1_56366982  total=12  flagged=11
  ✓ US2016207624A1_56407247  total=9  flagged=6
  ✓ US2016207625A1_51422096  total=12  flagged=12
  ✓ US2016214710A1_55218435  total=12  flagged=10
  ✓ US2016229531A1_56566535  total=12  flagged=12
  ✓ US2016236774A1_55168123  total=5  flagged=5
  ✓ US2016236775A1_56620788  total=8  flagged=8
  ✓ US2016244158A1_56690227  total=8  flagged=8
  ✓ US2016280369A1_53003021  total=8  flagged=8
  ✓ US2016288903A1_57015698  total=9  flagged=9
  ✓ US2016304194A1_57128418  total=11  flagged=11
  ✓ US2016304195A1_57129607  total=12  flagged=12
  ✓ US2016311522A1_57110590  total=12  flagged=12
  ✓ US2016311529A1_50071007  total=7  flagged=7
  ✓ US2016311545A1_57147406  total=8  flagged=8
  ✓ US2016325821A1_55968929  total=12  flagged=9
  ✓ US2016340038A1_57324322  total=12  flagged=12
  ✓ US2016347443A1_53479161  total=11  flagged=11
  ✓ US2016347447A1_56072277  total=6  flagged=6
  ✓ US2016347448A1_57396965  total=11  flagged=11
  ✓ US2016368600A1_57587574  total=12  flagged=12
  ✓ US2016368601A1_57587636  total=11  flagged=11
  ✓ US2017001721A1_57682863  total=11  flagged=11
  ✓ US2017057630A1_52472335  total=7  flagged=7
  ✓ US2017081037A1_56979435  total=7  flagged=7
  ✓ US2017101176A1_58498735  total=6  flagged=3
  ✓ US2017113795A1_58562387  total=4  flagged=4
  ✓ US2017121029A1_58634297  total=12  flagged=12

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

  ✓ US2017133771A1_53097343  total=7  flagged=7

/home/vasco/anaconda3/envs/doclayout_yolo/lib/python3.10/site-packages/PIL/Image.py:1137: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

## Cell 3b — Re-threshold existing results (no GPU needed)

Already-confirmed discards (`keep=False`) are **never** upgraded back.  
Only images currently `keep=True` are re-evaluated against the new threshold.  
Rewrites all JSONs and `triage_summary.csv` in-place.

In [ ]:
import importlib, triage_filter
importlib.reload(triage_filter)   # pick up src edits without restarting kernel

# ── Choose mode ───────────────────────────────────────────────────────────────
#
#   "add"   — rethreshold_existing: only ADDS new discards, never re-enables
#             anything already marked keep=False (safe, one-way)
#
#   "reset" — reset_threshold: re-derives keep from raw scores for ALL images,
#             works in both directions — use this to undo an over-aggressive run
#
MODE      = "reset"   # "add" | "reset"
THRESHOLD = 0.50      # tune this value
# ─────────────────────────────────────────────────────────────────────────────

if MODE == "add":
    triage_filter.rethreshold_existing(cfg, new_threshold=THRESHOLD)
elif MODE == "reset":
    triage_filter.reset_threshold(cfg, threshold=THRESHOLD)
else:
    print(f"Unknown MODE={MODE!r} — choose 'add' or 'reset'")

Reset complete (threshold=0.5): 13835 images | 1316 flagged (9.5%)
Summary rewritten: /mnt/storage_11tb/Drive_files_to_syncronize/3 - Images DataSets & Labelling Outputs/1639_DS/triage/triage_summary.csv

## Cell 5b — Lock/unlock (advanced)

Use **only** if you need direct control over locks outside the normal review flow.

| Action | Effect |
|--------|--------|
| `lock_discards` | Lock all current DISCARDs — they won't reappear in the viewer |
| `lock_keeps` | Lock all current KEEPs — aggressive threshold won't remove them |
| `unlock_all` | Clear every lock (full clean slate) |
| `stats` | Show current lock counts (no writes) |

> **Normal workflow:** use the Cell 6 viewer + the Commit cell at the bottom instead.

In [ ]:
import importlib, triage_filter
importlib.reload(triage_filter)

# ── Choose lock action ────────────────────────────────────────────────────────
#
#   "lock_discards"  — protect current DISCARDs; threshold raises cannot re-enable them
#   "lock_keeps"     — protect current KEEPs; threshold raises cannot discard them
#   "unlock_all"     — clear all locks (clean slate before a full reset)
#   "stats"          — just print the current lock counts (no writes)
#   None             — do nothing
#
LOCK_ACTION = "stats"   # change to "lock_discards", "lock_keeps", or "unlock_all"
# ─────────────────────────────────────────────────────────────────────────────

if LOCK_ACTION == "lock_discards":
    triage_filter.lock_discards(cfg)
elif LOCK_ACTION == "lock_keeps":
    triage_filter.lock_keeps(cfg)
elif LOCK_ACTION == "unlock_all":
    triage_filter.unlock_all(cfg)
elif LOCK_ACTION == "stats":
    triage_filter.locked_stats(cfg)
else:
    print("LOCK_ACTION not set — nothing done.")

In [ ]:
import json
import pandas as pd

triage_path = Path(cfg["paths"]["triage"])
summary_csv = triage_path / "triage_summary.csv"

if not summary_csv.exists():
    print("No triage_summary.csv found — run Cell 3 first.")
else:
    summary_df = pd.read_csv(summary_csv)

    total_images  = summary_df["total_images"].sum()
    total_flagged = summary_df["flagged_count"].sum()
    overall_ratio = total_flagged / max(1, total_images)

    print(f"Total images scored : {total_images}")
    print(f"Total flagged       : {total_flagged}")
    print(f"Overall flagged ratio: {overall_ratio:.1%}")
    print()

    # Show per-figure results for the 3 patents with the most flagged images
    top3 = summary_df.nlargest(3, "flagged_count")[["patent_id", "total_images", "flagged_count", "flagged_ratio"]]
    print("Top 3 patents by flagged count:")
    display(top3.reset_index(drop=True))
    print()

    for patent_id in top3["patent_id"]:
        json_path = triage_path / f"{patent_id}.json"
        if not json_path.exists():
            print(f"  {patent_id}: JSON not found")
            continue
        with open(json_path) as fh:
            data = json.load(fh)
        figures_df = pd.DataFrame(data["figures"])
        print(f"\n--- {patent_id}  (total={data['total']}  flagged={data['flagged']}) ---")
        display(figures_df[["file", "pred", "score_drawing", "score_table", "keep"]])

Total images scored : 13835
Total flagged       : 1316
Overall flagged ratio: 9.5%

Top 3 patents by flagged count:

                 patent_id  total_images  flagged_count  flagged_ratio
0    CN120191516A_96063272            12             12         1.0000
1  US2022048639A1_71127804            12             12         1.0000
2    CN116280179A_86786318            12             11         0.9167

--- CN120191516A_96063272  (total=12  flagged=12) ---

,file,pred,score_drawing,score_table,keep
0,CN120191516APAFP.png,table,0.4893,0.5107,False
1,CN120191516A_202411687048.png,table,0.4893,0.5107,False
2,CN120191516A_HDA0005149869780000021.png,table,0.4883,0.5117,False
3,CN120191516A_HDA0005149869780000031.png,table,0.4958,0.5044,False
4,CN120191516A_HDA0005149869780000041.png,table,0.4980,0.5020,False
5,CN120191516A_HDA0005149869780000051.png,table,0.4814,0.5186,False
6,CN120191516A_HDA0005149869780000052.png,table,0.4836,0.5166,False
7,CN120191516A_HDA0005149869780000053.png,table,0.4873,0.5127,False
8,CN120191516A_HDA0005149869780000061.png,table,0.4900,0.5098,False
9,CN120191516A_HDA0005149869780000062.png,table,0.4895,0.5103,False
10,CN120191516A_HDA0005149869780000071.png,table,0.4800,0.5200,False
11,CN120191516A_HDA0005149869780000081.png,table,0.4714,0.5288,False

--- US2022048639A1_71127804  (total=12  flagged=12) ---

                          file   pred  score_drawing  score_table   keep
0   US20220048639A1_D00000.png  table         0.4932       0.5068  False
1   US20220048639A1_D00001.png  table         0.4941       0.5059  False
2   US20220048639A1_D00002.png  table         0.4944       0.5054  False
3   US20220048639A1_D00003.png  table         0.4968       0.5034  False
4   US20220048639A1_D00004.png  table         0.4819       0.5181  False
5   US20220048639A1_D00005.png  table         0.4800       0.5200  False
6   US20220048639A1_D00006.png  table         0.4822       0.5176  False
7   US20220048639A1_D00007.png  table         0.4827       0.5176  False
8   US20220048639A1_D00008.png  table         0.4858       0.5142  False
9   US20220048639A1_D00009.png  table         0.4824       0.5176  False
10  US20220048639A1_D00010.png  table         0.4802       0.5200  False
11      US2022048639A1PAFP.png  table         0.4932       0.5068  False

--- CN116280179A_86786318  (total=12  flagged=11) ---

,file,pred,score_drawing,score_table,keep
0,CN116280179APAFP.png,table,0.4875,0.5127,False
1,CN116280179A_202310171305.png,table,0.4875,0.5127,False
2,CN116280179A_HDA0004099463590000012.png,table,0.4956,0.5044,False
3,CN116280179A_HDA0004099463590000021.png,table,0.4949,0.5054,False
4,CN116280179A_HDA0004099463590000022.png,table,0.4944,0.5054,False
5,CN116280179A_HDA0004099463590000031.png,table,0.4910,0.5093,False
6,CN116280179A_HDA0004099463590000032.png,table,0.4834,0.5166,False
7,CN116280179A_HDA0004099463590000041.png,drawing,0.5054,0.4949,True
8,CN116280179A_HDA0004099463590000042.png,table,0.4878,0.5122,False
9,CN116280179A_HDA0004099463590000051.png,table,0.4890,0.5107,False
10,CN116280179A_HDA0004099463590000052.png,table,0.4973,0.5024,False
11,CN116280179A_HDA0004099463590000061.png,table,0.4951,0.5049,False

## Cell 5 — Visual inspection: kept vs. discarded images

Shows the actual images for one patent so you can judge whether the threshold is working correctly.  
- **Green border** = kept (`keep=True`, `score_drawing ≥ threshold`)  
- **Red border** = discarded (`keep=False`)  

Change `INSPECT_PATENT` to any patent ID from the triage results, or leave it as `None` to auto-pick the first processed patent.

In [ ]:
import json
import math
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import ipywidgets as widgets
from IPython.display import display, clear_output
from pathlib import Path
from PIL import Image

triage_path = Path(cfg["paths"]["triage"])
raw_dir     = Path(cfg["paths"]["raw_images"])
MAX_COLS    = 4

# All processed patents, sorted
patent_ids = sorted(p.stem for p in triage_path.glob("*.json")
                    if p.stem != "triage_summary")
if not patent_ids:
    print("No triage JSON files found — run Cell 3 first.")
    raise SystemExit

print(f"Found {len(patent_ids)} processed patents. Use the buttons or dropdown to navigate.")

# ── Widgets ───────────────────────────────────────────────────────────────────
idx_state   = {"i": 0, "updating": False}   # flag prevents dropdown re-entrancy
out         = widgets.Output()
btn_prev    = widgets.Button(description="◀ Prev", button_style="info",  layout=widgets.Layout(width="120px"))
btn_next    = widgets.Button(description="Next ▶", button_style="info",  layout=widgets.Layout(width="120px"))
lbl_pos     = widgets.Label(value=f"1 / {len(patent_ids)}")
patent_dd   = widgets.Dropdown(options=patent_ids, value=patent_ids[0],
                                layout=widgets.Layout(width="360px"))

def show_patent(patent_id):
    json_path = triage_path / f"{patent_id}.json"
    with open(json_path) as fh:
        data = json.load(fh)
    figures = data["figures"]
    n       = len(figures)
    if n == 0:
        print(f"{patent_id}: no figures in triage JSON")
        return
    n_kept  = sum(1 for f in figures if f["keep"])
    n_disc  = n - n_kept

    n_cols = min(MAX_COLS, n)
    n_rows = math.ceil(n / n_cols)
    fig, axes = plt.subplots(n_rows, n_cols,
                             figsize=(n_cols * 1.8, n_rows * 2.0),
                             squeeze=False, dpi=80)
    flat_axes = [ax for row in axes for ax in row]

    patent_dir = raw_dir / patent_id
    for ax, fig_info in zip(flat_axes, figures):
        img_path = patent_dir / fig_info["file"]
        try:
            img = Image.open(img_path).convert("RGB")
            ax.imshow(img)
        except Exception:
            ax.text(0.5, 0.5, "not found", ha="center", va="center",
                    color="grey", transform=ax.transAxes)
        keep  = fig_info["keep"]
        color = "#2ecc71" if keep else "#e74c3c"
        label = "KEEP" if keep else "DISCARD"
        for spine in ax.spines.values():
            spine.set_edgecolor(color)
            spine.set_linewidth(4)
        ax.set_title(f"{fig_info['file']}\n{label}  {fig_info['score_drawing']:.3f}",
                     fontsize=7, color=color, pad=3)
        ax.set_xticks([]); ax.set_yticks([])

    for ax in flat_axes[n:]:
        ax.axis("off")

    keep_patch    = mpatches.Patch(color="#2ecc71", label=f"Kept ({n_kept})")
    discard_patch = mpatches.Patch(color="#e74c3c", label=f"Discarded ({n_disc})")
    fig.legend(handles=[keep_patch, discard_patch], loc="lower center",
               ncol=2, fontsize=10, frameon=False, bbox_to_anchor=(0.5, -0.01))
    fig.suptitle(f"{patent_id}  —  {n_kept}/{n} kept  (threshold={THRESHOLD})",
                 fontsize=12, fontweight="bold", y=1.01)
    plt.tight_layout()
    plt.show()

def refresh():
    i = idx_state["i"]
    # Update label and dropdown without triggering the observer callback
    lbl_pos.value = f"{i+1} / {len(patent_ids)}"
    idx_state["updating"] = True
    patent_dd.value = patent_ids[i]
    idx_state["updating"] = False
    with out:
        clear_output(wait=True)
        show_patent(patent_ids[i])

def on_prev(_):
    if idx_state["i"] > 0:
        idx_state["i"] -= 1
        refresh()

def on_next(_):
    if idx_state["i"] < len(patent_ids) - 1:
        idx_state["i"] += 1
        refresh()

def on_dropdown(change):
    # Only react to user-driven value changes, not programmatic ones from refresh()
    if change["name"] == "value" and not idx_state["updating"]:
        new_val = change["new"]
        if new_val in patent_ids:
            idx_state["i"] = patent_ids.index(new_val)
            refresh()

btn_prev.on_click(on_prev)
btn_next.on_click(on_next)
patent_dd.observe(on_dropdown)

nav_bar = widgets.HBox([btn_prev, lbl_pos, btn_next, patent_dd])
display(nav_bar, out)
refresh()

Found 1614 processed patents. Use the buttons or dropdown to navigate.

HBox(children=(Button(button_style='info', description='◀ Prev', layout=Layout(width='120px'), style=ButtonSty…

Output()

## Cell 6 — Review pending discards

Shows every image flagged as **discarded** that has **not yet been locked** (i.e. not reviewed in a previous session).

- **Red border** = DISCARD — will be permanently locked on Commit
- **Green border** = APPROVED — will be flipped to KEEP on Commit

Click any image to toggle between DISCARD and APPROVED.  Nothing is written to disk until you run the **Commit cell** below.

> Already-locked images (from previous sessions) are hidden — run `reset_review` in the Commit cell to bring them back.

In [ ]:
import importlib, triage_filter
importlib.reload(triage_filter)

import json, math, threading
import matplotlib
matplotlib.use("widget")
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, clear_output
from pathlib import Path
from PIL import Image

triage_path = Path(cfg["paths"]["triage"])
raw_dir     = Path(cfg["paths"]["raw_images"])

PAGE_SIZE = 70
MAX_COLS  = 7

# ── Load non-locked discarded images only ─────────────────────────────────────
# Images already locked (reviewed in a previous session) are hidden.
def load_pending_discards():
    result = []
    for json_path in sorted(triage_path.glob("*.json")):
        if json_path.stem == "triage_summary":
            continue
        with open(json_path) as fh:
            data = json.load(fh)
        for fig in data["figures"]:
            if not fig["keep"] and not fig.get("locked"):
                result.append({
                    "patent_id":     json_path.stem,
                    "file":          fig["file"],
                    "score_drawing": fig["score_drawing"],
                    "score_table":   fig["score_table"],
                })
    return result

discarded = load_pending_discards()

# approved: images the user clicked to flip to KEEP this session (not yet on disk)
approved  = set()

n_total = len(discarded)
n_pages = max(1, math.ceil(n_total / PAGE_SIZE))
print(f"Pending review (non-locked discards): {n_total}  ({n_pages} pages of {PAGE_SIZE})")
print("  Red border  = DISCARD  (will be locked on Commit)")
print("  Green border = APPROVED (will be set to KEEP on Commit)")
print("  Click any image to toggle it to APPROVED.")
print()
print("When done reviewing, run the LAST CELL to commit your decisions to disk.")

# ── Widgets ───────────────────────────────────────────────────────────────────
page_state = {"p": 0, "fig": None, "flat_axes": [], "batch": []}
out_disc   = widgets.Output()
btn_dp     = widgets.Button(description="◀ Prev", button_style="warning", layout=widgets.Layout(width="120px"))
btn_dn     = widgets.Button(description="Next ▶", button_style="warning", layout=widgets.Layout(width="120px"))
lbl_dp     = widgets.Label(value=f"Page 1 / {n_pages}")
lbl_info   = widgets.Label(value="")
lbl_counts = widgets.Label(value=f"Approved: 0 / {n_total}")

def _ax_color(entry):
    key = (entry["patent_id"], entry["file"])
    return ("#2ecc71", "APPROVED ✓") if key in approved else ("#e74c3c", "DISCARD")

def show_page(p):
    batch  = discarded[p * PAGE_SIZE : (p + 1) * PAGE_SIZE]
    n      = len(batch)
    if n == 0:
        return
    n_cols = min(MAX_COLS, n)
    n_rows = math.ceil(n / max(n_cols, 1))

    if page_state["fig"] is not None:
        plt.close(page_state["fig"])

    fig, axes = plt.subplots(n_rows, n_cols,
                             figsize=(n_cols * 1.8, n_rows * 2.0),
                             squeeze=False, dpi=80)
    flat_axes = [ax for row in axes for ax in row]
    page_state.update({"fig": fig, "flat_axes": flat_axes, "batch": batch})

    for ax, entry in zip(flat_axes, batch):
        img_path = raw_dir / entry["patent_id"] / entry["file"]
        try:
            img = Image.open(img_path).convert("RGB")
            ax.imshow(img)
        except Exception:
            ax.text(0.5, 0.5, "not found", ha="center", va="center",
                    color="grey", transform=ax.transAxes)
        ax.set_xticks([]); ax.set_yticks([])
        color, label = _ax_color(entry)
        for spine in ax.spines.values():
            spine.set_edgecolor(color)
            spine.set_linewidth(4)
        ax.set_title(
            f"{entry['patent_id']}\n{entry['file']}\n{label}  draw={entry['score_drawing']:.3f}",
            fontsize=6, color=color, pad=3
        )

    for ax in flat_axes[n:]:
        ax.axis("off")

    fig.suptitle(
        f"Pending discards — page {p+1}/{n_pages}  "
        f"(images {p*PAGE_SIZE+1}–{p*PAGE_SIZE+n} of {n_total})  "
        f"| Click image → APPROVED",
        fontsize=10, fontweight="bold"
    )
    plt.tight_layout()

    def on_click(event):
        if event.inaxes is None:
            return
        fa, ba = page_state["flat_axes"], page_state["batch"]
        for i, ax in enumerate(fa[:len(ba)]):
            if ax is event.inaxes:
                entry = ba[i]
                key   = (entry["patent_id"], entry["file"])
                # toggle
                if key in approved:
                    approved.discard(key)
                else:
                    approved.add(key)
                color, label = _ax_color(entry)
                for spine in ax.spines.values():
                    spine.set_edgecolor(color)
                    spine.set_linewidth(4)
                ax.set_title(
                    f"{entry['patent_id']}\n{entry['file']}\n{label}  draw={entry['score_drawing']:.3f}",
                    fontsize=6, color=color, pad=3
                )
                fig.canvas.draw_idle()
                lbl_info.value   = f"{'✓ APPROVED' if key in approved else '✗ back to DISCARD'}: {entry['patent_id']} / {entry['file']}"
                lbl_counts.value = f"Approved: {len(approved)} / {n_total}"
                return

    fig.canvas.mpl_connect("button_press_event", on_click)
    plt.show()

def refresh_disc(new_p):
    page_state["p"] = new_p
    lbl_dp.value    = f"Page {new_p + 1} / {n_pages}"
    lbl_info.value  = ""
    with out_disc:
        clear_output(wait=True)
        show_page(new_p)

btn_dp.on_click(lambda _: refresh_disc(page_state["p"] - 1) if page_state["p"] > 0 else None)
btn_dn.on_click(lambda _: refresh_disc(page_state["p"] + 1) if page_state["p"] < n_pages - 1 else None)

display(widgets.HBox([btn_dp, lbl_dp, btn_dn, lbl_counts, lbl_info]), out_disc)
refresh_disc(0)

Pending review (non-locked discards): 1979  (29 pages of 70)
  Red border  = DISCARD  (will be locked on Commit)
  Green border = APPROVED (will be set to KEEP on Commit)
  Click any image to toggle it to APPROVED.

When done reviewing, run the LAST CELL to commit your decisions to disk.

HBox(children=(Button(button_style='warning', description='◀ Prev', layout=Layout(width='120px'), style=Button…

Output()

## Cell 7 — Commit review decisions

Writes your Cell-6 review session to disk.

| `COMMIT_ACTION` | Effect |
|-----------------|--------|
| `"commit"` | Lock every APPROVED image as KEEP, lock every remaining DISCARD as discarded. They won't appear in the viewer again. |
| `"reset_review"` | Remove all discard locks — images reappear in Cell 6 for another review pass. Locked KEEPs are preserved. |
| `"stats"` | Show current lock counts (no writes). |

> **Typical session:**  
> 1. Run Cell 6, flip the false-positives to APPROVED  
> 2. Run this cell with `COMMIT_ACTION = "commit"`  
> 3. Next time you open the notebook, only *new* unreviewed discards show up  

> **To start fresh** (e.g. after changing threshold):  
> Set `COMMIT_ACTION = "reset_review"`, then re-run Cell 3b with `MODE = "reset"`

In [ ]:
import importlib, triage_filter
importlib.reload(triage_filter)

# ── Choose action ─────────────────────────────────────────────────────────────
#
#   "commit"        — write this session's decisions to disk (lock all)
#   "reset_review"  — unlock discard locks so they reappear in the viewer
#   "stats"         — show lock counts only (no writes)
#
COMMIT_ACTION = "commit"
# ─────────────────────────────────────────────────────────────────────────────

if COMMIT_ACTION == "commit":
    # `approved` is the set built up in Cell 6 above.
    # If you skipped Cell 6 this session, approved will be empty — all pending
    # discards will just be locked as discards (safe default).
    try:
        _approved = approved
    except NameError:
        _approved = set()
        print("⚠  Cell 6 was not run this session — no approvals recorded.")
    triage_filter.commit_review(cfg, _approved)

elif COMMIT_ACTION == "reset_review":
    triage_filter.reset_review(cfg)

elif COMMIT_ACTION == "stats":
    triage_filter.locked_stats(cfg)

else:
    print(f"Unknown COMMIT_ACTION={COMMIT_ACTION!r} — choose commit / reset_review / stats")

commit_review: 46 images flipped to KEEP (locked).
               1933 discards locked permanently.
Summary rewritten: /mnt/storage_11tb/Drive_files_to_syncronize/3 - Images DataSets & Labelling Outputs/1639_DS/triage/triage_summary.csv